const { g, verb, ex, q } = require("./_helpers");
const P = ["أنا (ana)", "أنتَ (anta)", "أنتِ (anti)", "هو (huwa)", "هي (hiya)", "نحن (naḥnu)", "أنتم (antum)", "هم (hum)"];
const V = (t, r, gl, lvl, f, o) => verb(P, t, gl, lvl, f, Object.assign({ r }, o));
const A = (c, final, name, sound, t, r, fr, en) => ({ c, final, name, sound, ex: { t, r, g: g(fr, en) } });
// Build [form, romanization] pairs from two parallel arrays.
const Z = (a, b) => a.map((x, i) => [x, b[i]]);
module.exports = {
  replace: ["grammar", "readings"],
  note: g("Arabe standard moderne (fuṣḥā). L'arabe s'écrit de droite à gauche ; les voyelles brèves ne sont généralement pas notées, d'où la translittération sous chaque mot.", "Modern Standard Arabic (fuṣḥā). Arabic is written right to left; short vowels are usually not written, hence the transliteration under each word."),
  alphabetNote: g("28 lettres, toutes des consonnes (ا و ي servent aussi de voyelles longues). La plupart des lettres s'attachent et changent de forme selon leur position.", "28 letters, all consonants (ا و ي also serve as long vowels). Most letters join and change shape depending on position."),
  alphabet: [
    A("ا", "ـا", "alif", "ā / support", "أب", "ab", "père", "father"), A("ب", "ـب", "bāʼ", "b", "باب", "bāb", "porte", "door"), A("ت", "ـت", "tāʼ", "t", "تفاح", "tuffāḥ", "pommes", "apples"),
    A("ث", "ـث", "thāʼ", "th (anglais think)", "ثلاثة", "thalātha", "trois", "three"), A("ج", "ـج", "jīm", "j", "جميل", "jamīl", "beau", "beautiful"), A("ح", "ـح", "ḥāʼ", "ḥ (h soufflé)", "حليب", "ḥalīb", "lait", "milk"),
    A("خ", "ـخ", "khāʼ", "kh (j espagnol)", "خبز", "khubz", "pain", "bread"), A("د", "ـد", "dāl", "d", "دار", "dār", "maison", "house"), A("ذ", "ـذ", "dhāl", "dh (anglais this)", "ذهب", "dhahab", "or", "gold"),
    A("ر", "ـر", "rāʼ", "r roulé", "رجل", "rajul", "homme", "man"), A("ز", "ـز", "zāy", "z", "زيت", "zayt", "huile", "oil"), A("س", "ـس", "sīn", "s", "سلام", "salām", "paix", "peace"),
    A("ش", "ـش", "shīn", "ch", "شمس", "shams", "soleil", "sun"), A("ص", "ـص", "ṣād", "ṣ (s emphatique)", "صديق", "ṣadīq", "ami", "friend"), A("ض", "ـض", "ḍād", "ḍ (d emphatique)", "ضيف", "ḍayf", "invité", "guest"),
    A("ط", "ـط", "ṭāʼ", "ṭ (t emphatique)", "طالب", "ṭālib", "étudiant", "student"), A("ظ", "ـظ", "ẓāʼ", "ẓ (dh emphatique)", "ظهر", "ẓuhr", "midi", "noon"), A("ع", "ـع", "ʻayn", "ʻ (constriction de gorge)", "عين", "ʻayn", "œil", "eye"),
    A("غ", "ـغ", "ghayn", "gh (r grasseyé)", "غرفة", "ghurfa", "chambre", "room"), A("ف", "ـف", "fāʼ", "f", "فم", "fam", "bouche", "mouth"), A("ق", "ـق", "qāf", "q (k profond)", "قلب", "qalb", "cœur", "heart"),
    A("ك", "ـك", "kāf", "k", "كتاب", "kitāb", "livre", "book"), A("ل", "ـل", "lām", "l", "ليل", "layl", "nuit", "night"), A("م", "ـم", "mīm", "m", "ماء", "māʼ", "eau", "water"),
    A("ن", "ـن", "nūn", "n", "نور", "nūr", "lumière", "light"), A("ه", "ـه", "hāʼ", "h", "هنا", "hunā", "ici", "here"), A("و", "ـو", "wāw", "w / ū", "ورد", "ward", "roses", "roses"), A("ي", "ـي", "yāʼ", "y / ī", "يد", "yad", "main", "hand"),
  ],
  grammar: [
    { id: "ar-article", level: "A1", icon: "🔤", title: g("L'article ال", "The article ال"), body: g("<p>Un seul article défini, <b>ال</b> (al-), invariable. Devant les lettres « solaires » (ت د ر س ش ن…), le l s'assimile : <i>الشمس</i> se lit <i>ash-shams</i>.</p>", "<p>One definite article, <b>ال</b> (al-), invariable. Before 'sun letters' (ت د ر س ش ن…) the l assimilates: <i>الشمس</i> is read <i>ash-shams</i>.</p>"), ex: [ex("الكتاب والقمر", "al-kitāb wa-l-qamar", "le livre et la lune", "the book and the moon")] },
    { id: "ar-nominale", level: "A1", icon: "🟰", title: g("La phrase nominale", "The nominal sentence"), body: g("<p>Pas de verbe « être » au présent : <i>البيت كبير</i> (la maison [est] grande). L'adjectif suit le nom et s'accorde en genre et en définition.</p>", "<p>No 'to be' in the present: <i>البيت كبير</i> (the house [is] big). Adjectives follow the noun and agree in gender and definiteness.</p>"), ex: [ex("أنا طالب.", "ana ṭālib.", "Je suis étudiant.", "I am a student.")] },
    { id: "ar-genre", level: "A1", icon: "⚥", title: g("Masculin et féminin (ة)", "Masculine and feminine (ة)"), body: g("<p>Le féminin se forme souvent avec <b>ة</b> (tāʼ marbūṭa) : <i>طالب → طالبة</i>, <i>كبير → كبيرة</i>.</p>", "<p>The feminine is often formed with <b>ة</b> (tāʼ marbūṭa): <i>طالب → طالبة</i>, <i>كبير → كبيرة</i>.</p>"), ex: [ex("مدينة جميلة", "madīna jamīla", "une belle ville", "a beautiful city")] },
    { id: "ar-racines", level: "A2", icon: "🌳", title: g("Les racines trilitères", "Three-letter roots"), body: g("<p>La plupart des mots dérivent d'une racine de trois consonnes. K-T-B (écrire) : <i>كتب</i> il a écrit, <i>كتاب</i> livre, <i>كاتب</i> écrivain, <i>مكتبة</i> bibliothèque, <i>مكتب</i> bureau.</p>", "<p>Most words come from a three-consonant root. K-T-B (write): <i>كتب</i> he wrote, <i>كتاب</i> book, <i>كاتب</i> writer, <i>مكتبة</i> library, <i>مكتب</i> office.</p>"), ex: [ex("الكاتب في المكتبة.", "al-kātib fi-l-maktaba.", "L'écrivain est à la bibliothèque.", "The writer is in the library.")] },
    { id: "ar-passe", level: "A2", icon: "⏪", title: g("Le passé (suffixes)", "The past (suffixes)"), body: g("<p>Le passé se forme avec des suffixes : <i>كتبتُ</i> (j'ai écrit), <i>كتبَ</i> (il a écrit), <i>كتبتْ</i> (elle a écrit), <i>كتبوا</i> (ils ont écrit).</p>", "<p>The past uses suffixes: <i>كتبتُ</i> (I wrote), <i>كتبَ</i> (he wrote), <i>كتبتْ</i> (she wrote), <i>كتبوا</i> (they wrote).</p>"), ex: [ex("ذهبنا إلى السوق.", "dhahabnā ilā as-sūq.", "Nous sommes allés au marché.", "We went to the market.")] },
    { id: "ar-present", level: "A2", icon: "⚡", title: g("Le présent (préfixes)", "The present (prefixes)"), body: g("<p>Le présent (inaccompli) utilise des préfixes : <i>أكتب، تكتب، يكتب، نكتب</i>. On ajoute <b>سـ</b> pour le futur : <i>سأكتب</i> (j'écrirai).</p>", "<p>The present (imperfect) uses prefixes: <i>أكتب، تكتب، يكتب، نكتب</i>. Add <b>سـ</b> for the future: <i>سأكتب</i> (I will write).</p>"), ex: [ex("هي تدرس العربية.", "hiya tadrusu al-ʻarabiyya.", "Elle étudie l'arabe.", "She studies Arabic.")] },
    { id: "ar-idafa", level: "B1", icon: "🔗", title: g("L'annexion (iḍāfa)", "The construct state (iḍāfa)"), body: g("<p>Deux noms juxtaposés expriment la possession ; seul le second prend l'article : <i>باب البيت</i> (la porte de la maison).</p>", "<p>Two nouns side by side express possession; only the second takes the article: <i>باب البيت</i> (the door of the house).</p>"), ex: [ex("مدير الشركة", "mudīr ash-sharika", "le directeur de l'entreprise", "the company director")] },
    { id: "ar-dialectes", level: "B2", icon: "🗺️", title: g("Fuṣḥā et dialectes", "Fuṣḥā and dialects"), body: g("<p>L'arabe standard sert à l'écrit, aux médias et aux discours. Au quotidien on parle un dialecte (égyptien, levantin, maghrébin, du Golfe…) : <i>كيف حالك</i> devient <i>إزيك</i> au Caire, <i>شنو</i>/<i>واش</i> au Maghreb.</p>", "<p>Standard Arabic is used for writing, media and speeches. Daily life happens in dialects (Egyptian, Levantine, Maghrebi, Gulf…): <i>كيف حالك</i> becomes <i>إزيك</i> in Cairo.</p>"), ex: [ex("كيف حالك؟", "kayfa ḥāluk?", "Comment vas-tu ?", "How are you?")] },
  ],
  conj: {
    tenses: [{ id: "passe", fr: "Accompli (passé)", en: "Perfect (past)" }, { id: "present", fr: "Inaccompli (présent)", en: "Imperfect (present)" }],
    verbs: [
      V("كتب", "kataba", g("écrire", "to write"), "A1", {
        passe: Z(["كتبتُ", "كتبتَ", "كتبتِ", "كتبَ", "كتبتْ", "كتبنا", "كتبتم", "كتبوا"], ["katabtu", "katabta", "katabti", "kataba", "katabat", "katabnā", "katabtum", "katabū"]),
        present: Z(["أكتب", "تكتب", "تكتبين", "يكتب", "تكتب", "نكتب", "تكتبون", "يكتبون"], ["aktubu", "taktubu", "taktubīna", "yaktubu", "taktubu", "naktubu", "taktubūna", "yaktubūna"]) }),
      V("درس", "darasa", g("étudier", "to study"), "A1", {
        passe: Z(["درستُ", "درستَ", "درستِ", "درسَ", "درستْ", "درسنا", "درستم", "درسوا"], ["darastu", "darasta", "darasti", "darasa", "darasat", "darasnā", "darastum", "darasū"]),
        present: Z(["أدرس", "تدرس", "تدرسين", "يدرس", "تدرس", "ندرس", "تدرسون", "يدرسون"], ["adrusu", "tadrusu", "tadrusīna", "yadrusu", "tadrusu", "nadrusu", "tadrusūna", "yadrusūna"]) }),
      V("ذهب", "dhahaba", g("aller", "to go"), "A1", {
        passe: Z(["ذهبتُ", "ذهبتَ", "ذهبتِ", "ذهبَ", "ذهبتْ", "ذهبنا", "ذهبتم", "ذهبوا"], ["dhahabtu", "dhahabta", "dhahabti", "dhahaba", "dhahabat", "dhahabnā", "dhahabtum", "dhahabū"]),
        present: Z(["أذهب", "تذهب", "تذهبين", "يذهب", "تذهب", "نذهب", "تذهبون", "يذهبون"], ["adhhabu", "tadhhabu", "tadhhabīna", "yadhhabu", "tadhhabu", "nadhhabu", "tadhhabūna", "yadhhabūna"]) }),
      V("شرب", "shariba", g("boire", "to drink"), "A1", {
        passe: Z(["شربتُ", "شربتَ", "شربتِ", "شربَ", "شربتْ", "شربنا", "شربتم", "شربوا"], ["sharibtu", "sharibta", "sharibti", "shariba", "sharibat", "sharibnā", "sharibtum", "sharibū"]),
        present: Z(["أشرب", "تشرب", "تشربين", "يشرب", "تشرب", "نشرب", "تشربون", "يشربون"], ["ashrabu", "tashrabu", "tashrabīna", "yashrabu", "tashrabu", "nashrabu", "tashrabūna", "yashrabūna"]) }),
      V("فتح", "fataḥa", g("ouvrir", "to open"), "A2", {
        passe: Z(["فتحتُ", "فتحتَ", "فتحتِ", "فتحَ", "فتحتْ", "فتحنا", "فتحتم", "فتحوا"], ["fataḥtu", "fataḥta", "fataḥti", "fataḥa", "fataḥat", "fataḥnā", "fataḥtum", "fataḥū"]),
        present: Z(["أفتح", "تفتح", "تفتحين", "يفتح", "تفتح", "نفتح", "تفتحون", "يفتحون"], ["aftaḥu", "taftaḥu", "taftaḥīna", "yaftaḥu", "taftaḥu", "naftaḥu", "taftaḥūna", "yaftaḥūna"]) }),
    ],
  },
  readings: [
    { id: "ar-r1", level: "A1", title: "عائلتي", t: "اسمي سارة. أنا من المغرب وأسكن في الرباط. عندي أخ وأخت. أبي مهندس وأمي معلمة. أحب القهوة والكتب.", r: "ismī Sāra. ana min al-Maghrib wa-askunu fī ar-Ribāṭ. ʻindī akh wa-ukht. abī muhandis wa-ummī muʻallima. uḥibbu al-qahwa wa-l-kutub.", tr: g("Je m'appelle Sara. Je viens du Maroc et j'habite à Rabat. J'ai un frère et une sœur. Mon père est ingénieur et ma mère est enseignante. J'aime le café et les livres.", "My name is Sara. I'm from Morocco and I live in Rabat. I have a brother and a sister. My father is an engineer and my mother is a teacher. I love coffee and books."),
      q: [q("Que fait la mère de Sara ?", "What does Sara's mother do?", [["Elle est enseignante", "She's a teacher"], ["Elle est ingénieure", "She's an engineer"], ["Elle est médecin", "She's a doctor"]], 0)] },
    { id: "ar-r2", level: "A2", title: "في السوق", t: "ذهبتُ أمس إلى السوق القديم مع صديقي. اشترينا خبزاً وزيتوناً وتمراً. شربنا شاياً بالنعناع في مقهى صغير. كان السوق مزدحماً لكنه جميل جداً.", r: "dhahabtu ams ilā as-sūq al-qadīm maʻa ṣadīqī. ishtaraynā khubzan wa-zaytūnan wa-tamran. sharibnā shāyan bi-n-naʻnāʻ fī maqhan ṣaghīr. kāna as-sūq muzdaḥiman lākinnahu jamīl jiddan.", tr: g("Hier je suis allé au vieux souk avec mon ami. Nous avons acheté du pain, des olives et des dattes. Nous avons bu un thé à la menthe dans un petit café. Le souk était bondé mais très beau.", "Yesterday I went to the old souk with my friend. We bought bread, olives and dates. We drank mint tea in a small café. The souk was crowded but very beautiful."),
      q: [q("Qu'ont-ils bu ?", "What did they drink?", [["Du thé à la menthe", "Mint tea"], ["Du café", "Coffee"], ["Du jus", "Juice"]], 0)] },
    { id: "ar-r3", level: "B1", title: "اللغة العربية", t: "العربية لغة رسمية في أكثر من عشرين دولة، ويتحدث بها أكثر من ثلاثمئة مليون شخص. وهي أيضاً إحدى اللغات الرسمية في الأمم المتحدة. أعطت العربية لغات كثيرة كلمات مثل: قطن، سكر، وجبر.", r: "al-ʻarabiyya lugha rasmiyya fī akthar min ʻishrīn dawla, wa-yataḥaddathu bihā akthar min thalāthimiʼat milyūn shakhṣ. wa-hiya ayḍan iḥdā al-lughāt ar-rasmiyya fi-l-umam al-muttaḥida. aʻṭat al-ʻarabiyya lughātin kathīra kalimāt mithl: quṭn, sukkar, wa-jabr.", tr: g("L'arabe est langue officielle dans plus de vingt pays et parlé par plus de trois cents millions de personnes. C'est aussi l'une des langues officielles de l'ONU. L'arabe a donné à de nombreuses langues des mots comme coton, sucre et algèbre.", "Arabic is an official language in more than twenty countries and is spoken by over three hundred million people. It is also one of the official UN languages. Arabic gave many languages words such as cotton, sugar and algebra."),
      q: [q("Quel mot vient de l'arabe ?", "Which word comes from Arabic?", [["Algèbre", "Algebra"], ["Fenêtre", "Window"], ["Montagne", "Mountain"]], 0)] },
  ],
  culture: [
    { id: "ar-c1", level: "A1", icon: "👋", title: g("Salutations", "Greetings"), body: g("<p><i>السلام عليكم</i> (la paix soit sur vous) reçoit la réponse <i>وعليكم السلام</i>. Les salutations sont longues : on demande des nouvelles de la famille.</p>", "<p><i>السلام عليكم</i> (peace be upon you) is answered <i>وعليكم السلام</i>. Greetings are long: people ask after the family.</p>") },
    { id: "ar-c2", level: "A2", icon: "🫖", title: g("L'hospitalité", "Hospitality"), body: g("<p>On offre thé, café ou dattes à l'invité. Refuser une première fois est poli ; on insiste ensuite.</p>", "<p>Guests are offered tea, coffee or dates. Refusing once is polite; the host then insists.</p>") },
    { id: "ar-c3", level: "B1", icon: "✒️", title: g("La calligraphie", "Calligraphy"), body: g("<p>La calligraphie (<i>khaṭṭ</i>) est un art majeur : styles naskh, thuluth, diwani, koufique ornent mosquées, livres et monnaies.</p>", "<p>Calligraphy (<i>khaṭṭ</i>) is a major art: naskh, thuluth, diwani and kufic styles decorate mosques, books and coins.</p>") },
  ],
};
