const { g, verb, ex, q } = require("./_helpers");
const P = ["εγώ", "εσύ", "αυτός / αυτή", "εμείς", "εσείς", "αυτοί / αυτές"];
const V = (t, r, gl, lvl, f, o) => verb(P, t, gl, lvl, f, Object.assign({ r }, o));
const A = (c, name, sound, t, r, fr, en) => ({ c, final: "", name, sound, ex: { t, r, g: g(fr, en) } });
module.exports = {
  replace: ["grammar", "readings"],
  note: g("Le grec moderne s'écrit avec l'alphabet grec (24 lettres). L'accent écrit (΄) indique la syllabe accentuée.", "Modern Greek uses the Greek alphabet (24 letters). The written accent (΄) marks the stressed syllable."),
  alphabetNote: g("24 lettres. Attention aux combinaisons : ου = ou, αι = è, ει/οι = i, μπ = b, ντ = d, γκ = g.", "24 letters. Watch the combinations: ου = oo, αι = e, ει/οι = i, μπ = b, ντ = d, γκ = g."),
  alphabet: [
    A("Α α", "álfa", "a", "αγάπη", "agápi", "amour", "love"), A("Β β", "víta", "v", "βιβλίο", "vivlío", "livre", "book"), A("Γ γ", "gáma", "gh / y", "γάλα", "gála", "lait", "milk"),
    A("Δ δ", "délta", "dh (anglais this)", "δέντρο", "déntro", "arbre", "tree"), A("Ε ε", "épsilon", "é", "ελιά", "eliá", "olive", "olive"), A("Ζ ζ", "zíta", "z", "ζωή", "zoí", "vie", "life"),
    A("Η η", "íta", "i", "ήλιος", "ílios", "soleil", "sun"), A("Θ θ", "thíta", "th (anglais think)", "θάλασσα", "thálassa", "mer", "sea"), A("Ι ι", "ióta", "i", "ιστορία", "istoría", "histoire", "history"),
    A("Κ κ", "kápa", "k", "καφές", "kafés", "café", "coffee"), A("Λ λ", "lámda", "l", "λεμόνι", "lemóni", "citron", "lemon"), A("Μ μ", "mi", "m", "μητέρα", "mitéra", "mère", "mother"),
    A("Ν ν", "ni", "n", "νερό", "neró", "eau", "water"), A("Ξ ξ", "xi", "ks", "ξένος", "xénos", "étranger", "foreigner"), A("Ο ο", "ómikron", "o", "όνομα", "ónoma", "nom", "name"),
    A("Π π", "pi", "p", "πατέρας", "patéras", "père", "father"), A("Ρ ρ", "ro", "r roulé", "ρολόι", "rolói", "horloge", "clock"), A("Σ σ ς", "sígma", "s", "σπίτι", "spíti", "maison", "house"),
    A("Τ τ", "taf", "t", "τραπέζι", "trapézi", "table", "table"), A("Υ υ", "ípsilon", "i", "ύπνος", "ípnos", "sommeil", "sleep"), A("Φ φ", "fi", "f", "φίλος", "fílos", "ami", "friend"),
    A("Χ χ", "chi", "kh", "χέρι", "chéri", "main", "hand"), A("Ψ ψ", "psi", "ps", "ψωμί", "psomí", "pain", "bread"), A("Ω ω", "oméga", "o", "ώρα", "óra", "heure", "hour"),
  ],
  grammar: [
    { id: "el-articles", level: "A1", icon: "⚥", title: g("Trois genres, des articles", "Three genders and articles"), body: g("<p><b>ο</b> (masculin), <b>η</b> (féminin), <b>το</b> (neutre) : <i>ο άντρας, η γυναίκα, το παιδί</i>. Indéfini : <i>ένας, μία, ένα</i>.</p>", "<p><b>ο</b> (masculine), <b>η</b> (feminine), <b>το</b> (neuter): <i>ο άντρας, η γυναίκα, το παιδί</i>. Indefinite: <i>ένας, μία, ένα</i>.</p>"), ex: [ex("Το σπίτι είναι μεγάλο.", "To spíti eínai megálo.", "La maison est grande.", "The house is big.")] },
    { id: "el-present", level: "A1", icon: "⚡", title: g("Le présent en -ω et en -άω", "Present in -ω and -άω"), body: g("<p>Groupe 1 : <i>γράφω, γράφεις, γράφει…</i> Groupe 2 : <i>μιλάω, μιλάς, μιλάει…</i> Le pronom sujet est souvent omis.</p>", "<p>Group 1: <i>γράφω, γράφεις, γράφει…</i> Group 2: <i>μιλάω, μιλάς, μιλάει…</i> Subject pronouns are often dropped.</p>"), ex: [ex("Μιλάτε ελληνικά;", "Miláte elliniká?", "Parlez-vous grec ?", "Do you speak Greek?")] },
    { id: "el-question", level: "A1", icon: "❓", title: g("Le point-virgule interrogatif", "The Greek question mark"), body: g("<p>En grec, le point d'interrogation s'écrit <b>;</b> — <i>Τι κάνεις;</i> (comment vas-tu ?).</p>", "<p>In Greek the question mark is written <b>;</b> — <i>Τι κάνεις;</i> (how are you?).</p>"), ex: [ex("Πού είναι η στάση;", "Poú eínai i stási?", "Où est l'arrêt ?", "Where is the stop?")] },
    { id: "el-cas", level: "A2", icon: "🧩", title: g("Les cas", "Cases"), body: g("<p>Nominatif, génitif, accusatif (et vocatif). <i>ο φίλος</i> (sujet) → <i>του φίλου</i> (du ami) → <i>τον φίλο</i> (COD).</p>", "<p>Nominative, genitive, accusative (and vocative). <i>ο φίλος</i> (subject) → <i>του φίλου</i> (of the friend) → <i>τον φίλο</i> (object).</p>"), ex: [ex("Βλέπω τον φίλο μου.", "Vlépo ton fílo mou.", "Je vois mon ami.", "I see my friend.")] },
    { id: "el-passe", level: "A2", icon: "⏪", title: g("L'aoriste (passé simple)", "The aorist (simple past)"), body: g("<p>Action ponctuelle passée ; souvent un ε- (augment) quand l'accent le demande : <i>γράφω → έγραψα</i>, <i>πίνω → ήπια</i>.</p>", "<p>A one-off past action; often an ε- (augment) when the stress needs it: <i>γράφω → έγραψα</i>, <i>πίνω → ήπια</i>.</p>"), ex: [ex("Χθες έγραψα ένα γράμμα.", "Chthes égrapsa éna grámma.", "Hier j'ai écrit une lettre.", "Yesterday I wrote a letter.")] },
    { id: "el-futur", level: "B1", icon: "⏩", title: g("Le futur avec θα", "The future with θα"), body: g("<p><b>θα</b> + verbe : <i>θα γράφω</i> (j'écrirai régulièrement), <i>θα γράψω</i> (j'écrirai une fois).</p>", "<p><b>θα</b> + verb: <i>θα γράφω</i> (I'll be writing), <i>θα γράψω</i> (I'll write once).</p>"), ex: [ex("Θα πάμε στη Σαντορίνη.", "Tha páme sti Santoríni.", "Nous irons à Santorin.", "We'll go to Santorini.")] },
  ],
  conj: {
    tenses: [{ id: "present", fr: "Présent", en: "Present" }, { id: "aoriste", fr: "Passé (aoriste)", en: "Past (aorist)" }],
    verbs: [
      V("είμαι", "eímai", g("être", "to be"), "A1", { present: [["είμαι", "eímai"], ["είσαι", "eísai"], ["είναι", "eínai"], ["είμαστε", "eímaste"], ["είστε", "eíste"], ["είναι", "eínai"]], aoriste: [["ήμουν", "ímoun"], ["ήσουν", "ísoun"], ["ήταν", "ítan"], ["ήμασταν", "ímastan"], ["ήσασταν", "ísastan"], ["ήταν", "ítan"]] }, { irregular: true }),
      V("έχω", "écho", g("avoir", "to have"), "A1", { present: [["έχω", "écho"], ["έχεις", "écheis"], ["έχει", "échei"], ["έχουμε", "échoume"], ["έχετε", "échete"], ["έχουν", "échoun"]], aoriste: [["είχα", "eícha"], ["είχες", "eíches"], ["είχε", "eíche"], ["είχαμε", "eíchame"], ["είχατε", "eíchate"], ["είχαν", "eíchan"]] }, { irregular: true }),
      V("γράφω", "gráfo", g("écrire", "to write"), "A1", { present: [["γράφω", "gráfo"], ["γράφεις", "gráfeis"], ["γράφει", "gráfei"], ["γράφουμε", "gráfoume"], ["γράφετε", "gráfete"], ["γράφουν", "gráfoun"]], aoriste: [["έγραψα", "égrapsa"], ["έγραψες", "égrapses"], ["έγραψε", "égrapse"], ["γράψαμε", "grápsame"], ["γράψατε", "grápsate"], ["έγραψαν", "égrapsan"]] }),
      V("μιλάω", "miláo", g("parler", "to speak"), "A1", { present: [["μιλάω", "miláo"], ["μιλάς", "milás"], ["μιλάει", "milái"], ["μιλάμε", "miláme"], ["μιλάτε", "miláte"], ["μιλάνε", "miláne"]], aoriste: [["μίλησα", "mílisa"], ["μίλησες", "mílises"], ["μίλησε", "mílise"], ["μιλήσαμε", "milísame"], ["μιλήσατε", "milísate"], ["μίλησαν", "mílisan"]] }),
    ],
  },
  readings: [
    { id: "el-r1", level: "A1", title: "Η Μαρία", t: "Με λένε Μαρία. Μένω στην Αθήνα. Έχω έναν αδελφό. Το πρωί πίνω καφέ και διαβάζω. Το καλοκαίρι πάω στη θάλασσα.", r: "Me léne María. Méno stin Athína. Écho énan adelfó. To proí píno kafé kai diavázo. To kalokaíri páo sti thálassa.", tr: g("Je m'appelle Maria. J'habite à Athènes. J'ai un frère. Le matin, je bois un café et je lis. L'été, je vais à la mer.", "My name is Maria. I live in Athens. I have a brother. In the morning I drink coffee and read. In summer I go to the sea."),
      q: [q("Où va Maria l'été ?", "Where does Maria go in summer?", [["À la mer", "To the sea"], ["À la montagne", "To the mountains"], ["À Paris", "To Paris"]], 0)] },
    { id: "el-r2", level: "A2", title: "Στο νησί", t: "Πέρσι πήγαμε σε ένα μικρό νησί. Κολυμπήσαμε κάθε μέρα και φάγαμε φρέσκο ψάρι στην ταβέρνα. Το βράδυ περπατούσαμε στο λιμάνι. Ήταν οι καλύτερες διακοπές μας.", r: "Pérsi pígame se éna mikró nisí. Kolympísame káthe méra kai fágame frésko psári stin tavérna. To vrády perpatoúsame sto limáni. Ítan oi kalýteres diakopés mas.", tr: g("L'an dernier, nous sommes allés sur une petite île. Nous avons nagé tous les jours et mangé du poisson frais à la taverne. Le soir, nous nous promenions sur le port. C'étaient nos meilleures vacances.", "Last year we went to a small island. We swam every day and ate fresh fish at the taverna. In the evening we walked along the harbour. They were our best holidays."),
      q: [q("Où mangeaient-ils du poisson ?", "Where did they eat fish?", [["À la taverne", "At the taverna"], ["À l'hôtel", "At the hotel"], ["Sur le bateau", "On the boat"]], 0)] },
    { id: "el-r3", level: "B1", title: "Λέξεις από τα ελληνικά", t: "Πολλές λέξεις σε άλλες γλώσσες έρχονται από τα ελληνικά: δημοκρατία, φιλοσοφία, τηλέφωνο, μουσική. Τα ελληνικά γράφονται εδώ και πάνω από τρεις χιλιάδες χρόνια, και είναι μία από τις παλαιότερες γλώσσες της Ευρώπης.", r: "Pollés léxeis se álles glósses érchontai apó ta elliniká: dimokratía, filosofía, tiléfono, mousikí. Ta elliniká gráfontai edó kai páno apó treis chiliádes chrónia, kai eínai mía apó tis palaióteres glósses tis Evrópis.", tr: g("Beaucoup de mots d'autres langues viennent du grec : démocratie, philosophie, téléphone, musique. Le grec s'écrit depuis plus de trois mille ans et c'est l'une des plus anciennes langues d'Europe.", "Many words in other languages come from Greek: democracy, philosophy, telephone, music. Greek has been written for more than three thousand years and is one of Europe's oldest languages."),
      q: [q("Depuis combien de temps le grec s'écrit-il ?", "How long has Greek been written?", [["Plus de 3000 ans", "Over 3,000 years"], ["500 ans", "500 years"], ["1000 ans", "1,000 years"]], 0)] },
  ],
  culture: [
    { id: "el-c1", level: "A1", icon: "🙆", title: g("Oui et non", "Yes and no"), body: g("<p><i>Ναι</i> (né) veut dire « oui » ! « Non » se dit <i>όχι</i>, souvent accompagné d'un petit mouvement de tête vers le haut.</p>", "<p><i>Ναι</i> (neh) means 'yes'! 'No' is <i>όχι</i>, often with a small upward tilt of the head.</p>") },
    { id: "el-c2", level: "A2", icon: "🎉", title: g("La fête du prénom", "Name days"), body: g("<p>On fête son <i>γιορτή</i>, le jour du saint dont on porte le nom, souvent plus que son anniversaire : <i>Χρόνια πολλά!</i></p>", "<p>People celebrate their <i>γιορτή</i>, the day of their namesake saint, often more than birthdays: <i>Χρόνια πολλά!</i></p>") },
    { id: "el-c3", level: "B1", icon: "☕", title: g("Le café frappé", "Frappé coffee"), body: g("<p>Inventé en 1957 à Thessalonique, le frappé (café instantané battu avec glaçons) reste un symbole de l'été grec, concurrencé par le freddo espresso.</p>", "<p>Invented in 1957 in Thessaloniki, the frappé (instant coffee shaken with ice) remains a symbol of Greek summer, now rivalled by the freddo espresso.</p>") },
  ],
};
