const { g, verb, ex, q } = require("./_helpers");
const P = ["मैं (main)", "तू (tū)", "वह (vah)", "हम (ham)", "तुम (tum)", "आप (āp)", "वे (ve)"];
const V = (t, r, gl, lvl, f, o) => verb(P, t, gl, lvl, f, Object.assign({ r }, o));
const A = (c, name, sound, t, r, fr, en) => ({ c, final: "", name, sound, ex: { t, r, g: g(fr, en) } });
const Z = (a, b) => a.map((x, i) => [x, b[i]]);
// present habitual (masculine) = stem + ता/ते + auxiliary
const PH = (st, r) => Z([st + "ता हूँ", st + "ता है", st + "ता है", st + "ते हैं", st + "ते हो", st + "ते हैं", st + "ते हैं"], [r + "tā hūn̐", r + "tā hai", r + "tā hai", r + "te hain̐", r + "te ho", r + "te hain̐", r + "te hain̐"]);
module.exports = {
  replace: ["grammar", "readings"],
  note: g("L'hindi s'écrit en devanagari, de gauche à droite, sous une barre horizontale. Les formes verbales données sont au masculin ; au féminin, -ā/-e deviennent -ī.", "Hindi is written in Devanagari, left to right, under a horizontal bar. Verb forms shown are masculine; for feminine, -ā/-e become -ī."),
  alphabetNote: g("Chaque consonne contient un « a » inhérent ; les autres voyelles s'y attachent par des signes (क, का, कि, की, कु…).", "Each consonant carries an inherent 'a'; other vowels attach as signs (क, का, कि, की, कु…)."),
  alphabet: [
    A("अ", "a", "a bref", "अब", "ab", "maintenant", "now"), A("आ", "ā", "a long", "आम", "ām", "mangue", "mango"), A("इ", "i", "i bref", "इमली", "imlī", "tamarin", "tamarind"), A("ई", "ī", "i long", "ईख", "īkh", "canne à sucre", "sugar cane"),
    A("उ", "u", "ou bref", "उल्लू", "ullū", "hibou", "owl"), A("ऊ", "ū", "ou long", "ऊन", "ūn", "laine", "wool"), A("ए", "e", "é", "एक", "ek", "un", "one"), A("ऐ", "ai", "è", "ऐनक", "ainak", "lunettes", "glasses"),
    A("ओ", "o", "o", "ओस", "os", "rosée", "dew"), A("औ", "au", "ô ouvert", "औरत", "aurat", "femme", "woman"),
    A("क", "ka", "k", "कमल", "kamal", "lotus", "lotus"), A("ख", "kha", "k aspiré", "खाना", "khānā", "nourriture", "food"), A("ग", "ga", "g", "गाय", "gāy", "vache", "cow"), A("घ", "gha", "g aspiré", "घर", "ghar", "maison", "house"),
    A("च", "ca", "tch", "चाय", "cāy", "thé", "tea"), A("छ", "cha", "tch aspiré", "छत", "chat", "toit", "roof"), A("ज", "ja", "dj", "जल", "jal", "eau", "water"), A("झ", "jha", "dj aspiré", "झंडा", "jhanḍā", "drapeau", "flag"),
    A("ट", "ṭa", "t rétroflexe", "टमाटर", "ṭamāṭar", "tomate", "tomato"), A("ड", "ḍa", "d rétroflexe", "डर", "ḍar", "peur", "fear"), A("त", "ta", "t dental", "तारा", "tārā", "étoile", "star"), A("द", "da", "d dental", "दिन", "din", "jour", "day"),
    A("न", "na", "n", "नाम", "nām", "nom", "name"), A("प", "pa", "p", "पानी", "pānī", "eau", "water"), A("फ", "pha", "p aspiré / f", "फल", "phal", "fruit", "fruit"), A("ब", "ba", "b", "बच्चा", "baccā", "enfant", "child"),
    A("भ", "bha", "b aspiré", "भारत", "bhārat", "Inde", "India"), A("म", "ma", "m", "माँ", "mān̐", "mère", "mother"), A("य", "ya", "y", "यात्रा", "yātrā", "voyage", "journey"), A("र", "ra", "r", "रात", "rāt", "nuit", "night"),
    A("ल", "la", "l", "लड़का", "laṛkā", "garçon", "boy"), A("व", "va", "v / w", "वन", "van", "forêt", "forest"), A("श", "śa", "ch", "शहर", "śahar", "ville", "city"), A("स", "sa", "s", "सड़क", "saṛak", "route", "road"), A("ह", "ha", "h", "हाथ", "hāth", "main", "hand"),
  ],
  grammar: [
    { id: "hi-ordre", level: "A1", icon: "➡️", title: g("Sujet – objet – verbe", "Subject – object – verb"), body: g("<p>Le verbe se place à la fin : <i>मैं चाय पीता हूँ</i> (je bois du thé). On utilise des postpositions au lieu de prépositions : <i>घर में</i> (dans la maison).</p>", "<p>The verb goes last: <i>मैं चाय पीता हूँ</i> (I drink tea). Hindi uses postpositions instead of prepositions: <i>घर में</i> (in the house).</p>"), ex: [ex("मैं दिल्ली में रहता हूँ।", "main dillī men rahtā hūn̐.", "J'habite à Delhi.", "I live in Delhi.")] },
    { id: "hi-hona", level: "A1", icon: "🟰", title: g("Le verbe होना (être)", "The verb होना (to be)"), body: g("<p><i>मैं हूँ, तू है, वह है, हम हैं, तुम हो, आप हैं, वे हैं</i>. Passé : <i>था / थी / थे</i>.</p>", "<p><i>मैं हूँ, तू है, वह है, हम हैं, तुम हो, आप हैं, वे हैं</i>. Past: <i>था / थी / थे</i>.</p>"), ex: [ex("आप कहाँ से हैं?", "āp kahān̐ se hain̐?", "D'où êtes-vous ?", "Where are you from?")] },
    { id: "hi-genre", level: "A1", icon: "⚥", title: g("Genre et accord", "Gender and agreement"), body: g("<p>Deux genres. Beaucoup de masculins en -ā (<i>लड़का</i>), de féminins en -ī (<i>लड़की</i>). Adjectifs et verbes s'accordent : <i>अच्छा लड़का, अच्छी लड़की</i>.</p>", "<p>Two genders. Many masculines end in -ā (<i>लड़का</i>), feminines in -ī (<i>लड़की</i>). Adjectives and verbs agree: <i>अच्छा लड़का, अच्छी लड़की</i>.</p>"), ex: [ex("वह पढ़ती है।", "vah paṛhtī hai.", "Elle étudie.", "She studies.")] },
    { id: "hi-politesse", level: "A1", icon: "🙏", title: g("तू, तुम, आप", "तू, तुम, आप"), body: g("<p>Trois degrés de « tu » : <b>तू</b> (très intime), <b>तुम</b> (familier), <b>आप</b> (poli, par défaut avec les inconnus).</p>", "<p>Three levels of 'you': <b>तू</b> (very intimate), <b>तुम</b> (familiar), <b>आप</b> (polite, default with strangers).</p>"), ex: [ex("आप कैसे हैं?", "āp kaise hain̐?", "Comment allez-vous ?", "How are you?")] },
    { id: "hi-futur", level: "A2", icon: "⏩", title: g("Le futur", "The future"), body: g("<p>Terminaisons -ऊँगा, -एगा, -एँगे, -ओगे : <i>मैं जाऊँगा</i> (j'irai), <i>वह आएगा</i> (il viendra).</p>", "<p>Endings -ऊँगा, -एगा, -एँगे, -ओगे: <i>मैं जाऊँगा</i> (I will go), <i>वह आएगा</i> (he will come).</p>"), ex: [ex("हम कल मिलेंगे।", "ham kal milenge.", "Nous nous verrons demain.", "We'll meet tomorrow.")] },
    { id: "hi-ne", level: "B1", icon: "🎯", title: g("Le passé et la particule ने", "The past and the particle ने"), body: g("<p>Au passé des verbes transitifs, le sujet prend <b>ने</b> et le verbe s'accorde avec l'objet : <i>मैंने चाय पी</i> (j'ai bu du thé — पी au féminin car चाय est féminin).</p>", "<p>In the past of transitive verbs, the subject takes <b>ने</b> and the verb agrees with the object: <i>मैंने चाय पी</i> (I drank tea — पी is feminine because चाय is).</p>"), ex: [ex("उसने किताब पढ़ी।", "usne kitāb paṛhī.", "Il/Elle a lu le livre.", "He/She read the book.")] },
  ],
  conj: {
    tenses: [{ id: "present", fr: "Présent habituel", en: "Present habitual" }, { id: "futur", fr: "Futur", en: "Future" }],
    verbs: [
      V("होना", "honā", g("être", "to be"), "A1", { present: Z(["हूँ", "है", "है", "हैं", "हो", "हैं", "हैं"], ["hūn̐", "hai", "hai", "hain̐", "ho", "hain̐", "hain̐"]), futur: Z(["होऊँगा", "होगा", "होगा", "होंगे", "होगे", "होंगे", "होंगे"], ["hoūn̐gā", "hogā", "hogā", "honge", "hoge", "honge", "honge"]) }, { irregular: true }),
      V("बोलना", "bolnā", g("parler", "to speak"), "A1", { present: PH("बोल", "bol"), futur: Z(["बोलूँगा", "बोलेगा", "बोलेगा", "बोलेंगे", "बोलोगे", "बोलेंगे", "बोलेंगे"], ["bolūn̐gā", "bolegā", "bolegā", "bolenge", "bologe", "bolenge", "bolenge"]) }),
      V("खाना", "khānā", g("manger", "to eat"), "A1", { present: PH("खा", "khā"), futur: Z(["खाऊँगा", "खाएगा", "खाएगा", "खाएँगे", "खाओगे", "खाएँगे", "खाएँगे"], ["khāūn̐gā", "khāegā", "khāegā", "khāen̐ge", "khāoge", "khāen̐ge", "khāen̐ge"]) }),
      V("जाना", "jānā", g("aller", "to go"), "A1", { present: PH("जा", "jā"), futur: Z(["जाऊँगा", "जाएगा", "जाएगा", "जाएँगे", "जाओगे", "जाएँगे", "जाएँगे"], ["jāūn̐gā", "jāegā", "jāegā", "jāen̐ge", "jāoge", "jāen̐ge", "jāen̐ge"]) }),
      V("करना", "karnā", g("faire", "to do"), "A1", { present: PH("कर", "kar"), futur: Z(["करूँगा", "करेगा", "करेगा", "करेंगे", "करोगे", "करेंगे", "करेंगे"], ["karūn̐gā", "karegā", "karegā", "karenge", "karoge", "karenge", "karenge"]) }),
    ],
  },
  readings: [
    { id: "hi-r1", level: "A1", title: "मेरा परिवार", t: "मेरा नाम राहुल है। मैं मुंबई में रहता हूँ। मेरे परिवार में पाँच लोग हैं। मेरे पिताजी डॉक्टर हैं और मेरी माँ शिक्षिका हैं। मुझे क्रिकेट बहुत पसंद है।", r: "merā nām Rāhul hai. main Mumbaī men rahtā hūn̐. mere parivār men pān̐c log hain̐. mere pitājī ḍokṭar hain̐ aur merī mān̐ śikṣikā hain̐. mujhe krikeṭ bahut pasand hai.", tr: g("Je m'appelle Rahul. J'habite à Mumbai. Nous sommes cinq dans ma famille. Mon père est médecin et ma mère est enseignante. J'adore le cricket.", "My name is Rahul. I live in Mumbai. There are five people in my family. My father is a doctor and my mother is a teacher. I really like cricket."),
      q: [q("Quel sport aime Rahul ?", "Which sport does Rahul like?", [["Le cricket", "Cricket"], ["Le football", "Football"], ["Le tennis", "Tennis"]], 0)] },
    { id: "hi-r2", level: "A2", title: "दिवाली", t: "दिवाली रोशनी का त्योहार है। लोग अपने घर साफ़ करते हैं और दीये जलाते हैं। शाम को परिवार के सब लोग मिठाई खाते हैं और पटाखे चलाते हैं। यह त्योहार अक्टूबर या नवंबर में आता है।", r: "divālī rośnī kā tyohār hai. log apne ghar sāf karte hain̐ aur dīye jalāte hain̐. śām ko parivār ke sab log miṭhāī khāte hain̐ aur paṭākhe calāte hain̐. yah tyohār akṭūbar yā navambar men ātā hai.", tr: g("Diwali est la fête des lumières. Les gens nettoient leur maison et allument des lampes à huile. Le soir, toute la famille mange des sucreries et fait éclater des pétards. Cette fête a lieu en octobre ou en novembre.", "Diwali is the festival of lights. People clean their homes and light oil lamps. In the evening the whole family eats sweets and sets off firecrackers. The festival falls in October or November."),
      q: [q("Qu'allume-t-on pour Diwali ?", "What do people light for Diwali?", [["Des lampes à huile", "Oil lamps"], ["Des feux de camp", "Bonfires"], ["Des bougies d'anniversaire", "Birthday candles"]], 0)] },
    { id: "hi-r3", level: "B1", title: "भारतीय रेल", t: "भारतीय रेल दुनिया के सबसे बड़े रेल नेटवर्कों में से एक है। हर दिन दो करोड़ से ज़्यादा लोग ट्रेन से यात्रा करते हैं। स्टेशन पर चायवाले \"चाय, चाय\" पुकारते हैं। लंबी यात्रा में लोग खाना बाँटते हैं और नए दोस्त बनाते हैं।", r: "bhāratīy rel duniyā ke sabse baṛe rel neṭvarkon men se ek hai. har din do karoṛ se zyādā log ṭren se yātrā karte hain̐. sṭeśan par cāyvāle \"cāy, cāy\" pukārte hain̐. lambī yātrā men log khānā bān̐ṭte hain̐ aur nae dost banāte hain̐.", tr: g("Les chemins de fer indiens sont l'un des plus grands réseaux du monde. Chaque jour, plus de vingt millions de personnes voyagent en train. Dans les gares, les vendeurs de thé crient « chai, chai ». Pendant les longs trajets, on partage la nourriture et on se fait de nouveaux amis.", "Indian Railways is one of the largest rail networks in the world. Every day more than twenty million people travel by train. At stations, tea sellers call out 'chai, chai'. On long journeys people share food and make new friends."),
      q: [q("Que font les gens pendant les longs trajets ?", "What do people do on long journeys?", [["Ils partagent la nourriture", "They share food"], ["Ils dorment toujours", "They always sleep"], ["Ils travaillent", "They work"]], 0)] },
  ],
  culture: [
    { id: "hi-c1", level: "A1", icon: "🙏", title: g("Namaste", "Namaste"), body: g("<p>On salue en joignant les mains devant la poitrine : <i>नमस्ते</i>. Le suffixe <b>-जी</b> ajoute du respect : <i>पिताजी</i>, <i>शर्मा जी</i>.</p>", "<p>People greet with palms joined at the chest: <i>नमस्ते</i>. The suffix <b>-जी</b> adds respect: <i>पिताजी</i>, <i>शर्मा जी</i>.</p>") },
    { id: "hi-c2", level: "A2", icon: "🎬", title: g("Bollywood", "Bollywood"), body: g("<p>Mumbai produit des centaines de films par an, pleins de chansons et de danses. Ils mêlent souvent hindi et anglais (« Hinglish »).</p>", "<p>Mumbai produces hundreds of films a year, full of songs and dances. They often mix Hindi and English ('Hinglish').</p>") },
    { id: "hi-c3", level: "B1", icon: "🗣️", title: g("Hindi et ourdou", "Hindi and Urdu"), body: g("<p>À l'oral, l'hindi et l'ourdou sont très proches. L'hindi s'écrit en devanagari et puise dans le sanskrit, l'ourdou en alphabet perso-arabe avec plus de mots persans.</p>", "<p>Spoken Hindi and Urdu are very close. Hindi is written in Devanagari and draws on Sanskrit; Urdu uses Perso-Arabic script with more Persian vocabulary.</p>") },
  ],
};
