const { g, ex, q, G, R, C } = require("./_helpers");
module.exports = {
  replace: ["grammar", "readings"],
  note: g("L'indonésien s'écrit en alphabet latin et se lit comme il s'écrit. Pas de conjugaison, pas de genre, pas de tons : idéal pour débuter.", "Indonesian uses the Latin alphabet and is read as written. No conjugation, gender or tones: great for beginners."),
  grammar: [
    G("id-simple", "A1", "🧱", ["Pas de conjugaison", "No conjugation"], ["<p>Le verbe ne change jamais : <i>saya makan, dia makan, kami makan</i>. Le temps s'exprime avec <b>sudah</b> (déjà), <b>sedang</b> (en train de), <b>akan</b> (futur).</p>", "<p>Verbs never change: <i>saya makan, dia makan, kami makan</i>. Time is shown with <b>sudah</b> (already), <b>sedang</b> (in the middle of), <b>akan</b> (will).</p>"], [ex("Saya sudah makan.", "", "J'ai déjà mangé.", "I've already eaten.")]),
    G("id-pluriel", "A1", "👥", ["Le pluriel par redoublement", "Plural by reduplication"], ["<p>On répète le nom : <i>anak-anak</i> (des enfants), <i>buku-buku</i> (des livres). Souvent inutile si le contexte suffit.</p>", "<p>Repeat the noun: <i>anak-anak</i> (children), <i>buku-buku</i> (books). Often unnecessary if context is clear.</p>"], [ex("Anak-anak bermain di taman.", "", "Les enfants jouent au parc.", "The children play in the park.")]),
    G("id-kami", "A1", "🫂", ["kami ou kita ?", "kami or kita?"], ["<p>Deux « nous » : <b>kita</b> inclut l'interlocuteur, <b>kami</b> l'exclut.</p>", "<p>Two 'we's: <b>kita</b> includes the listener, <b>kami</b> excludes them.</p>"], [ex("Ayo kita pergi!", "", "Allons-y (toi et moi) !", "Let's go (you and me)!")]),
    G("id-negation", "A1", "🚫", ["tidak et bukan", "tidak and bukan"], ["<p><b>tidak</b> nie les verbes et adjectifs (<i>tidak mahal</i>), <b>bukan</b> nie les noms (<i>bukan guru</i>).</p>", "<p><b>tidak</b> negates verbs and adjectives (<i>tidak mahal</i>), <b>bukan</b> negates nouns (<i>bukan guru</i>).</p>"], [ex("Saya bukan orang Jakarta.", "", "Je ne suis pas de Jakarta.", "I'm not from Jakarta.")]),
    G("id-affixes", "B1", "🧩", ["Les affixes me- et di-", "The affixes me- and di-"], ["<p><b>me-</b> forme l'actif (<i>membaca</i>, lire), <b>di-</b> le passif (<i>dibaca</i>, être lu). <b>ber-</b> exprime un état ou une activité (<i>bermain</i>, jouer).</p>", "<p><b>me-</b> forms the active (<i>membaca</i>, to read), <b>di-</b> the passive (<i>dibaca</i>, to be read). <b>ber-</b> marks a state or activity (<i>bermain</i>, to play).</p>"], [ex("Buku ini dibaca oleh banyak orang.", "", "Ce livre est lu par beaucoup de gens.", "This book is read by many people.")]),
  ],
  readings: [
    R("id-r1", "A1", "Di Bali", "Nama saya Made. Saya tinggal di Bali. Setiap pagi saya minum kopi dan makan nasi goreng. Saya bekerja di hotel dekat pantai. Pada hari Minggu saya berselancar dengan teman-teman.", "", ["Je m'appelle Made. J'habite à Bali. Tous les matins, je bois un café et je mange du riz frit. Je travaille dans un hôtel près de la plage. Le dimanche, je fais du surf avec des amis.", "My name is Made. I live in Bali. Every morning I drink coffee and eat fried rice. I work in a hotel near the beach. On Sundays I surf with friends."],
      [q("Où travaille Made ?", "Where does Made work?", [["Dans un hôtel", "In a hotel"], ["Dans une école", "In a school"], ["Dans un restaurant", "In a restaurant"]], 0)]),
    R("id-r2", "A2", "Negara kepulauan", "Indonesia adalah negara kepulauan terbesar di dunia, dengan lebih dari tujuh belas ribu pulau. Di sana ada ratusan bahasa daerah, tetapi bahasa Indonesia digunakan sebagai bahasa persatuan. Semboyan negara ini adalah \"Bhinneka Tunggal Ika\", artinya berbeda-beda tetapi tetap satu.", "", ["L'Indonésie est le plus grand pays archipel du monde, avec plus de dix-sept mille îles. On y parle des centaines de langues régionales, mais l'indonésien sert de langue d'unité. La devise du pays est « Bhinneka Tunggal Ika » : unis dans la diversité.", "Indonesia is the world's largest archipelago nation, with more than seventeen thousand islands. Hundreds of regional languages are spoken, but Indonesian serves as the language of unity. The national motto is 'Bhinneka Tunggal Ika': unity in diversity."],
      [q("Que signifie la devise nationale ?", "What does the national motto mean?", [["Unis dans la diversité", "Unity in diversity"], ["Liberté et travail", "Freedom and work"], ["Dieu et patrie", "God and country"]], 0)]),
  ],
  culture: [
    C("id-c1", "A1", "🤝", ["La main droite", "The right hand"], ["<p>On donne, reçoit et mange avec la main droite ; pointer du doigt est impoli, on utilise le pouce.</p>", "<p>Give, receive and eat with the right hand; pointing with a finger is rude, use your thumb.</p>"]),
    C("id-c2", "A2", "🎭", ["Le batik et le wayang", "Batik and wayang"], ["<p>Le batik (tissu teint à la cire) et le wayang (théâtre d'ombres) sont inscrits au patrimoine de l'UNESCO.</p>", "<p>Batik (wax-resist dyed cloth) and wayang (shadow puppetry) are UNESCO-listed heritage.</p>"]),
    C("id-c3", "B1", "🕐", ["Jam karet", "Jam karet"], ["<p>« L'heure élastique » : une vision souple de la ponctualité, surtout dans les situations informelles.</p>", "<p>'Rubber time': a relaxed view of punctuality, especially in informal settings.</p>"]),
  ],
};
