const { g, verb, ex, q } = require("./_helpers");
const A = (c, name, sound, t, r, fr, en) => ({ c, final: "", name, sound, ex: { t, r, g: g(fr, en) } });
// Japanese verbs don't change with the person: one row per form.
const F = ["neutre / plain", "poli / polite", "négatif poli / polite neg.", "passé poli / polite past", "forme en -te", "volitif poli / let's"];
const V = (t, r, gl, lvl, forms, o) => verb(F, t, gl, lvl, { formes: forms }, Object.assign({ r }, o));
module.exports = {
  replace: ["grammar", "readings"],
  note: g("Le japonais mêle trois écritures : hiragana (grammaire, mots natifs), katakana (mots étrangers) et kanji (sens). La romanisation Hepburn est affichée sous chaque mot.", "Japanese mixes three scripts: hiragana (grammar, native words), katakana (loanwords) and kanji (meaning). Hepburn romanization is shown under each word."),
  alphabetNote: g("Les 46 hiragana de base. Chaque signe est une syllabe ; les katakana ont les mêmes sons (カ = か).", "The 46 basic hiragana. Each sign is a syllable; katakana have the same sounds (カ = か)."),
  alphabet: [
    A("あ", "a", "a", "あめ", "ame", "pluie", "rain"), A("い", "i", "i", "いぬ", "inu", "chien", "dog"), A("う", "u", "u", "うみ", "umi", "mer", "sea"), A("え", "e", "e", "えき", "eki", "gare", "station"), A("お", "o", "o", "おちゃ", "ocha", "thé", "tea"),
    A("か", "ka", "ka", "かさ", "kasa", "parapluie", "umbrella"), A("き", "ki", "ki", "き", "ki", "arbre", "tree"), A("く", "ku", "ku", "くち", "kuchi", "bouche", "mouth"), A("け", "ke", "ke", "けさ", "kesa", "ce matin", "this morning"), A("こ", "ko", "ko", "こども", "kodomo", "enfant", "child"),
    A("さ", "sa", "sa", "さかな", "sakana", "poisson", "fish"), A("し", "shi", "shi", "しお", "shio", "sel", "salt"), A("す", "su", "su", "すし", "sushi", "sushi", "sushi"), A("せ", "se", "se", "せかい", "sekai", "monde", "world"), A("そ", "so", "so", "そら", "sora", "ciel", "sky"),
    A("た", "ta", "ta", "たまご", "tamago", "œuf", "egg"), A("ち", "chi", "chi", "ちず", "chizu", "carte", "map"), A("つ", "tsu", "tsu", "つき", "tsuki", "lune", "moon"), A("て", "te", "te", "て", "te", "main", "hand"), A("と", "to", "to", "とり", "tori", "oiseau", "bird"),
    A("な", "na", "na", "なつ", "natsu", "été", "summer"), A("に", "ni", "ni", "にく", "niku", "viande", "meat"), A("ぬ", "nu", "nu", "ぬの", "nuno", "tissu", "cloth"), A("ね", "ne", "ne", "ねこ", "neko", "chat", "cat"), A("の", "no", "no", "のみもの", "nomimono", "boisson", "drink"),
    A("は", "ha", "ha (wa comme particule)", "はな", "hana", "fleur", "flower"), A("ひ", "hi", "hi", "ひと", "hito", "personne", "person"), A("ふ", "fu", "fu", "ふゆ", "fuyu", "hiver", "winter"), A("へ", "he", "he (e comme particule)", "へや", "heya", "chambre", "room"), A("ほ", "ho", "ho", "ほん", "hon", "livre", "book"),
    A("ま", "ma", "ma", "まど", "mado", "fenêtre", "window"), A("み", "mi", "mi", "みず", "mizu", "eau", "water"), A("む", "mu", "mu", "むし", "mushi", "insecte", "insect"), A("め", "me", "me", "め", "me", "œil", "eye"), A("も", "mo", "mo", "もり", "mori", "forêt", "forest"),
    A("や", "ya", "ya", "やま", "yama", "montagne", "mountain"), A("ゆ", "yu", "yu", "ゆき", "yuki", "neige", "snow"), A("よ", "yo", "yo", "よる", "yoru", "nuit", "night"),
    A("ら", "ra", "ra", "らいねん", "rainen", "l'an prochain", "next year"), A("り", "ri", "ri", "りんご", "ringo", "pomme", "apple"), A("る", "ru", "ru", "るす", "rusu", "absence", "being out"), A("れ", "re", "re", "れきし", "rekishi", "histoire", "history"), A("ろ", "ro", "ro", "ろく", "roku", "six", "six"),
    A("わ", "wa", "wa", "わたし", "watashi", "je", "I"), A("を", "wo", "o (particule d'objet)", "ほんをよむ", "hon o yomu", "lire un livre", "read a book"), A("ん", "n", "n", "ほん", "hon", "livre", "book"),
  ],
  alphabetExtra: { title: g("Katakana courants", "Common katakana"), items: [
    { c: "コーヒー", name: "kōhī", sound: "café / coffee", say: "コーヒー" }, { c: "テレビ", name: "terebi", sound: "télé / TV", say: "テレビ" }, { c: "パン", name: "pan", sound: "pain / bread", say: "パン" },
    { c: "ホテル", name: "hoteru", sound: "hôtel / hotel", say: "ホテル" }, { c: "タクシー", name: "takushī", sound: "taxi", say: "タクシー" }, { c: "フランス", name: "furansu", sound: "France", say: "フランス" },
  ] },
  grammar: [
    { id: "ja-ordre", level: "A1", icon: "➡️", title: g("Le verbe à la fin", "Verb at the end"), body: g("<p>Ordre sujet – objet – verbe : <i>わたしはすしをたべます</i> (je mange des sushis). Le sujet est souvent omis s'il est évident.</p>", "<p>Subject – object – verb order: <i>わたしはすしをたべます</i> (I eat sushi). The subject is often dropped when obvious.</p>"), ex: [ex("毎朝コーヒーを飲みます。", "Maiasa kōhī o nomimasu.", "Je bois du café tous les matins.", "I drink coffee every morning.")] },
    { id: "ja-particules", level: "A1", icon: "🏷️", title: g("Les particules は, が, を, に, で", "Particles は, が, を, に, で"), body: g("<p><b>は</b> (wa) : thème. <b>が</b> : sujet mis en avant. <b>を</b> (o) : objet. <b>に</b> : destination, heure. <b>で</b> : lieu de l'action, moyen.</p>", "<p><b>は</b> (wa): topic. <b>が</b>: highlighted subject. <b>を</b> (o): object. <b>に</b>: destination, time. <b>で</b>: place of action, means.</p>"), ex: [ex("図書館で本を読みます。", "Toshokan de hon o yomimasu.", "Je lis un livre à la bibliothèque.", "I read a book at the library.")] },
    { id: "ja-desu", level: "A1", icon: "🟰", title: g("です et la forme polie ます", "です and the polite ます form"), body: g("<p><b>です</b> = « être » poli : <i>がくせいです</i>. Les verbes polis finissent en <b>ます</b> ; négatif <b>ません</b>, passé <b>ました</b>.</p>", "<p><b>です</b> = polite 'to be': <i>がくせいです</i>. Polite verbs end in <b>ます</b>; negative <b>ません</b>, past <b>ました</b>.</p>"), ex: [ex("昨日は行きませんでした。", "Kinō wa ikimasen deshita.", "Hier, je n'y suis pas allé.", "I didn't go yesterday.")] },
    { id: "ja-ka", level: "A1", icon: "❓", title: g("Les questions avec か", "Questions with か"), body: g("<p>Ajoutez <b>か</b> à la fin d'une phrase polie : <i>日本人ですか</i> (êtes-vous japonais ?).</p>", "<p>Add <b>か</b> at the end of a polite sentence: <i>日本人ですか</i> (Are you Japanese?).</p>"), ex: [ex("トイレはどこですか。", "Toire wa doko desu ka.", "Où sont les toilettes ?", "Where is the toilet?")] },
    { id: "ja-adjectifs", level: "A2", icon: "🎨", title: g("Adjectifs en い et en な", "い- and な-adjectives"), body: g("<p>Les adjectifs en <b>い</b> se conjuguent : <i>たかい → たかくない → たかかった</i>. Ceux en <b>な</b> prennent な devant un nom : <i>しずかなへや</i>.</p>", "<p><b>い</b>-adjectives inflect: <i>たかい → たかくない → たかかった</i>. <b>な</b>-adjectives take な before a noun: <i>しずかなへや</i> (a quiet room).</p>"), ex: [ex("この映画はおもしろかったです。", "Kono eiga wa omoshirokatta desu.", "Ce film était intéressant.", "This film was interesting.")] },
    { id: "ja-te", level: "A2", icon: "🔗", title: g("La forme en て", "The て-form"), body: g("<p>Elle relie des actions (<i>起きて、食べて、出かけます</i>), sert à demander (<i>見てください</i>) et à former l'action en cours (<i>読んでいます</i>).</p>", "<p>It links actions (<i>起きて、食べて、出かけます</i>), makes requests (<i>見てください</i>) and forms ongoing actions (<i>読んでいます</i>).</p>"), ex: [ex("ちょっと待ってください。", "Chotto matte kudasai.", "Attendez un instant, s'il vous plaît.", "Please wait a moment.")] },
    { id: "ja-plain", level: "B1", icon: "🗣️", title: g("Forme neutre (entre amis)", "Plain form (casual speech)"), body: g("<p>Entre proches on utilise la forme de dictionnaire : <i>たべる / たべない / たべた</i>. Elle est aussi obligatoire dans les subordonnées : <i>日本に行ったことがあります</i>.</p>", "<p>Among friends you use the dictionary form: <i>たべる / たべない / たべた</i>. It's also required in subordinate clauses: <i>日本に行ったことがあります</i> (I have been to Japan).</p>"), ex: [ex("明日、映画を見に行く？", "Ashita, eiga o mi ni iku?", "Tu vas voir un film demain ?", "Going to see a film tomorrow?")] },
    { id: "ja-keigo", level: "B2", icon: "🙇", title: g("Le keigo (langage honorifique)", "Keigo (honorific language)"), body: g("<p>On élève l'autre (<i>いらっしゃる</i> au lieu de <i>いる/来る</i>) et on s'abaisse soi-même (<i>まいる</i>, <i>いたす</i>). Indispensable au travail et dans les commerces.</p>", "<p>You raise the other person (<i>いらっしゃる</i> instead of <i>いる/来る</i>) and lower yourself (<i>まいる</i>, <i>いたす</i>). Essential at work and in shops.</p>"), ex: [ex("少々お待ちください。", "Shōshō omachi kudasai.", "Veuillez patienter un instant.", "Please wait a moment (very polite).")] },
  ],
  conj: {
    note: g("Les verbes japonais ne changent pas selon la personne : on apprend leurs formes (neutre, polie, négative, passée, en -te…).", "Japanese verbs don't change with the person: you learn their forms (plain, polite, negative, past, te-form…)."),
    tenses: [{ id: "formes", fr: "Formes principales", en: "Main forms" }],
    verbs: [
      V("食べる", "taberu", g("manger", "to eat"), "A1", [["食べる", "taberu"], ["食べます", "tabemasu"], ["食べません", "tabemasen"], ["食べました", "tabemashita"], ["食べて", "tabete"], ["食べましょう", "tabemashō"]]),
      V("飲む", "nomu", g("boire", "to drink"), "A1", [["飲む", "nomu"], ["飲みます", "nomimasu"], ["飲みません", "nomimasen"], ["飲みました", "nomimashita"], ["飲んで", "nonde"], ["飲みましょう", "nomimashō"]]),
      V("行く", "iku", g("aller", "to go"), "A1", [["行く", "iku"], ["行きます", "ikimasu"], ["行きません", "ikimasen"], ["行きました", "ikimashita"], ["行って", "itte"], ["行きましょう", "ikimashō"]], { irregular: true }),
      V("見る", "miru", g("voir, regarder", "to see, watch"), "A1", [["見る", "miru"], ["見ます", "mimasu"], ["見ません", "mimasen"], ["見ました", "mimashita"], ["見て", "mite"], ["見ましょう", "mimashō"]]),
      V("書く", "kaku", g("écrire", "to write"), "A2", [["書く", "kaku"], ["書きます", "kakimasu"], ["書きません", "kakimasen"], ["書きました", "kakimashita"], ["書いて", "kaite"], ["書きましょう", "kakimashō"]]),
      V("する", "suru", g("faire", "to do"), "A1", [["する", "suru"], ["します", "shimasu"], ["しません", "shimasen"], ["しました", "shimashita"], ["して", "shite"], ["しましょう", "shimashō"]], { irregular: true }),
      V("来る", "kuru", g("venir", "to come"), "A1", [["来る", "kuru"], ["来ます", "kimasu"], ["来ません", "kimasen"], ["来ました", "kimashita"], ["来て", "kite"], ["来ましょう", "kimashō"]], { irregular: true }),
    ],
  },
  readings: [
    { id: "ja-r1", level: "A1", title: "わたしの一日", t: "わたしはマリです。フランス人です。毎朝七時に起きます。朝ごはんを食べて、電車で会社に行きます。夜は家で本を読みます。", r: "Watashi wa Mari desu. Furansujin desu. Maiasa shichiji ni okimasu. Asagohan o tabete, densha de kaisha ni ikimasu. Yoru wa ie de hon o yomimasu.", tr: g("Je suis Marie. Je suis française. Tous les matins je me lève à sept heures. Je prends le petit-déjeuner puis je vais au bureau en train. Le soir, je lis un livre à la maison.", "I'm Marie. I'm French. Every morning I get up at seven. I have breakfast, then go to the office by train. In the evening I read a book at home."),
      q: [q("Comment Marie va-t-elle au travail ?", "How does Marie get to work?", [["En train", "By train"], ["À pied", "On foot"], ["En voiture", "By car"]], 0)] },
    { id: "ja-r2", level: "A2", title: "京都旅行", t: "先週、友だちと京都へ行きました。古いお寺や神社をたくさん見ました。金閣寺はとてもきれいでした。昼ごはんに湯豆腐を食べました。少し寒かったですが、楽しかったです。", r: "Senshū, tomodachi to Kyōto e ikimashita. Furui otera ya jinja o takusan mimashita. Kinkakuji wa totemo kirei deshita. Hirugohan ni yudōfu o tabemashita. Sukoshi samukatta desu ga, tanoshikatta desu.", tr: g("La semaine dernière, je suis allé à Kyoto avec un ami. Nous avons vu beaucoup de vieux temples et sanctuaires. Le Pavillon d'or était magnifique. Au déjeuner, nous avons mangé du tofu bouilli. Il faisait un peu froid, mais c'était agréable.", "Last week I went to Kyoto with a friend. We saw many old temples and shrines. The Golden Pavilion was very beautiful. For lunch we ate simmered tofu. It was a little cold, but it was fun."),
      q: [q("Quel temps faisait-il ?", "What was the weather like?", [["Un peu froid", "A little cold"], ["Très chaud", "Very hot"], ["Il pleuvait", "Rainy"]], 0)] },
    { id: "ja-r3", level: "B1", title: "お花見", t: "春になると、日本中で桜が咲きます。人々は公園に集まって、桜の木の下でお弁当を食べたり、お酒を飲んだりします。これを「お花見」と言います。桜はすぐに散ってしまうので、人生のはかなさの象徴でもあります。", r: "Haru ni naru to, Nihonjū de sakura ga sakimasu. Hitobito wa kōen ni atsumatte, sakura no ki no shita de obentō o tabetari, osake o nondari shimasu. Kore o “ohanami” to iimasu. Sakura wa sugu ni chitte shimau node, jinsei no hakanasa no shōchō demo arimasu.", tr: g("Au printemps, les cerisiers fleurissent dans tout le Japon. Les gens se réunissent dans les parcs, mangent des bentos et boivent du saké sous les arbres. C'est le « hanami ». Comme les fleurs tombent vite, elles symbolisent aussi la fugacité de la vie.", "When spring comes, cherry trees bloom all over Japan. People gather in parks to eat bento and drink sake under the trees. This is called 'hanami'. Because the blossoms fall quickly, they also symbolise the fleeting nature of life."),
      q: [q("Que symbolisent les fleurs de cerisier ?", "What do cherry blossoms symbolise?", [["La fugacité de la vie", "The fleeting nature of life"], ["La richesse", "Wealth"], ["L'hiver", "Winter"]], 0)] },
  ],
  culture: [
    { id: "ja-c1", level: "A1", icon: "🙇", title: g("La courbette", "Bowing"), body: g("<p>On salue, remercie et s'excuse en s'inclinant. Plus l'inclinaison est profonde, plus le respect est grand.</p>", "<p>People greet, thank and apologise by bowing. The deeper the bow, the greater the respect.</p>") },
    { id: "ja-c2", level: "A2", icon: "👟", title: g("Les chaussures", "Shoes"), body: g("<p>On retire ses chaussures dans l'entrée (<i>genkan</i>) des maisons, de certains restaurants et temples. Des chaussons spéciaux existent pour les toilettes.</p>", "<p>Shoes come off in the entrance (<i>genkan</i>) of homes, some restaurants and temples. There are even special slippers for the toilet.</p>") },
    { id: "ja-c3", level: "B1", icon: "🍱", title: g("Itadakimasu", "Itadakimasu"), body: g("<p>Avant de manger on dit <i>いただきます</i>, après <i>ごちそうさまでした</i>. Ne plantez jamais les baguettes verticalement dans le riz (geste funéraire).</p>", "<p>Before eating you say <i>いただきます</i>, afterwards <i>ごちそうさまでした</i>. Never stick chopsticks upright in rice (a funeral gesture).</p>") },
  ],
};
