const { g, verb, ex, q } = require("./_helpers");
const A = (c, name, sound, t, r, fr, en) => ({ c, final: "", name, sound, ex: { t, r, g: g(fr, en) } });
const F = ["forme de base / dictionary", "poli (-요) / polite", "passé poli / polite past", "futur poli / polite future", "formel (-ㅂ니다) / formal", "négatif poli / polite neg."];
const V = (t, r, gl, lvl, forms, o) => verb(F, t, gl, lvl, { formes: forms }, Object.assign({ r }, o));
module.exports = {
  replace: ["grammar", "readings"],
  note: g("Le coréen s'écrit en hangeul : des lettres regroupées en blocs syllabiques (ㅎ+ㅏ+ㄴ = 한). La romanisation révisée est affichée sous chaque mot.", "Korean is written in Hangul: letters grouped into syllable blocks (ㅎ+ㅏ+ㄴ = 한). Revised Romanization is shown under each word."),
  alphabetNote: g("Le hangeul a été créé en 1443 par le roi Sejong. 14 consonnes et 10 voyelles de base : on peut l'apprendre en quelques jours.", "Hangul was created in 1443 by King Sejong. 14 basic consonants and 10 basic vowels: you can learn it in a few days."),
  alphabet: [
    A("ㄱ", "giyeok", "g / k", "가방", "gabang", "sac", "bag"), A("ㄴ", "nieun", "n", "나무", "namu", "arbre", "tree"), A("ㄷ", "digeut", "d / t", "다리", "dari", "jambe / pont", "leg / bridge"),
    A("ㄹ", "rieul", "r / l", "라면", "ramyeon", "nouilles", "ramen"), A("ㅁ", "mieum", "m", "물", "mul", "eau", "water"), A("ㅂ", "bieup", "b / p", "바다", "bada", "mer", "sea"),
    A("ㅅ", "siot", "s", "사과", "sagwa", "pomme", "apple"), A("ㅇ", "ieung", "muet / ng", "우유", "uyu", "lait", "milk"), A("ㅈ", "jieut", "j", "집", "jip", "maison", "house"),
    A("ㅊ", "chieut", "ch", "차", "cha", "voiture / thé", "car / tea"), A("ㅋ", "kieuk", "k (aspiré)", "커피", "keopi", "café", "coffee"), A("ㅌ", "tieut", "t (aspiré)", "토마토", "tomato", "tomate", "tomato"),
    A("ㅍ", "pieup", "p (aspiré)", "포도", "podo", "raisin", "grapes"), A("ㅎ", "hieut", "h", "하늘", "haneul", "ciel", "sky"),
    A("ㅏ", "a", "a", "아기", "agi", "bébé", "baby"), A("ㅑ", "ya", "ya", "야구", "yagu", "baseball", "baseball"), A("ㅓ", "eo", "ʌ (o ouvert)", "어머니", "eomeoni", "mère", "mother"),
    A("ㅕ", "yeo", "yʌ", "여름", "yeoreum", "été", "summer"), A("ㅗ", "o", "o", "오이", "oi", "concombre", "cucumber"), A("ㅛ", "yo", "yo", "요리", "yori", "cuisine", "cooking"),
    A("ㅜ", "u", "ou", "우산", "usan", "parapluie", "umbrella"), A("ㅠ", "yu", "you", "유리", "yuri", "verre", "glass"), A("ㅡ", "eu", "ɯ", "그림", "geurim", "dessin", "picture"), A("ㅣ", "i", "i", "이름", "ireum", "nom", "name"),
  ],
  grammar: [
    { id: "ko-ordre", level: "A1", icon: "➡️", title: g("Sujet – objet – verbe", "Subject – object – verb"), body: g("<p>Le verbe vient toujours en dernier : <i>저는 김치를 먹어요</i> (je mange du kimchi).</p>", "<p>The verb always comes last: <i>저는 김치를 먹어요</i> (I eat kimchi).</p>"), ex: [ex("저는 학교에 가요.", "Jeoneun hakgyoe gayo.", "Je vais à l'école.", "I go to school.")] },
    { id: "ko-particules", level: "A1", icon: "🏷️", title: g("Particules 은/는, 이/가, 을/를", "Particles 은/는, 이/가, 을/를"), body: g("<p>Après consonne / après voyelle : thème <b>은/는</b>, sujet <b>이/가</b>, objet <b>을/를</b>, lieu/destination <b>에</b>, lieu d'action <b>에서</b>.</p>", "<p>After consonant / after vowel: topic <b>은/는</b>, subject <b>이/가</b>, object <b>을/를</b>, place/destination <b>에</b>, place of action <b>에서</b>.</p>"), ex: [ex("친구가 카페에서 커피를 마셔요.", "Chinguga kapeeseo keopireul masyeoyo.", "Mon ami boit un café au café.", "My friend drinks coffee at the café.")] },
    { id: "ko-politesse", level: "A1", icon: "🙇", title: g("Niveaux de politesse", "Politeness levels"), body: g("<p><b>-요</b> : poli courant (<i>감사해요</i>). <b>-ㅂ니다/습니다</b> : formel (<i>감사합니다</i>). Sans terminaison : familier, entre amis (<i>고마워</i>).</p>", "<p><b>-요</b>: everyday polite (<i>감사해요</i>). <b>-ㅂ니다/습니다</b>: formal (<i>감사합니다</i>). No ending: casual, among friends (<i>고마워</i>).</p>"), ex: [ex("만나서 반갑습니다.", "Mannaseo bangapseumnida.", "Enchanté (formel).", "Nice to meet you (formal).")] },
    { id: "ko-passe", level: "A2", icon: "⏪", title: g("Le passé -았/었어요", "Past -았/었어요"), body: g("<p>Radical avec ㅏ/ㅗ → <b>-았어요</b> (<i>갔어요</i>) ; autres → <b>-었어요</b> (<i>먹었어요</i>) ; 하다 → <b>했어요</b>.</p>", "<p>Stem with ㅏ/ㅗ → <b>-았어요</b> (<i>갔어요</i>); others → <b>-었어요</b> (<i>먹었어요</i>); 하다 → <b>했어요</b>.</p>"), ex: [ex("어제 영화를 봤어요.", "Eoje yeonghwareul bwasseoyo.", "Hier j'ai vu un film.", "Yesterday I watched a film.")] },
    { id: "ko-negation", level: "A2", icon: "🚫", title: g("La négation 안 / 못", "Negation 안 / 못"), body: g("<p><b>안</b> + verbe : ne pas (volonté) ; <b>못</b> + verbe : ne pas pouvoir. <i>안 가요 / 못 가요</i>.</p>", "<p><b>안</b> + verb: not (by choice); <b>못</b> + verb: cannot. <i>안 가요 / 못 가요</i>.</p>"), ex: [ex("저는 매운 음식을 못 먹어요.", "Jeoneun maeun eumsigeul mot meogeoyo.", "Je ne peux pas manger épicé.", "I can't eat spicy food.")] },
    { id: "ko-futur", level: "B1", icon: "⏩", title: g("Futur et intention -(으)ㄹ 거예요", "Future -(으)ㄹ 거예요"), body: g("<p>Pour un projet ou une supposition : <i>내일 비가 올 거예요</i> (il pleuvra demain).</p>", "<p>For plans or guesses: <i>내일 비가 올 거예요</i> (it'll rain tomorrow).</p>"), ex: [ex("주말에 부산에 갈 거예요.", "Jumare Busane gal geoyeyo.", "Ce week-end, j'irai à Busan.", "I'll go to Busan this weekend.")] },
    { id: "ko-honorifiques", level: "B2", icon: "👑", title: g("L'honorifique -(으)시-", "Honorific -(으)시-"), body: g("<p>Pour parler respectueusement d'une personne âgée ou supérieure : <i>할머니께서 주무세요</i> (grand-mère dort).</p>", "<p>To speak respectfully about an elder or superior: <i>할머니께서 주무세요</i> (Grandmother is sleeping).</p>"), ex: [ex("선생님, 어디 가세요?", "Seonsaengnim, eodi gaseyo?", "Où allez-vous, professeur ?", "Where are you going, teacher?")] },
  ],
  conj: {
    note: g("Les verbes coréens ne changent pas selon la personne mais selon le temps et le niveau de politesse.", "Korean verbs don't change with the person but with tense and politeness level."),
    tenses: [{ id: "formes", fr: "Formes principales", en: "Main forms" }],
    verbs: [
      V("가다", "gada", g("aller", "to go"), "A1", [["가다", "gada"], ["가요", "gayo"], ["갔어요", "gasseoyo"], ["갈 거예요", "gal geoyeyo"], ["갑니다", "gamnida"], ["안 가요", "an gayo"]]),
      V("먹다", "meokda", g("manger", "to eat"), "A1", [["먹다", "meokda"], ["먹어요", "meogeoyo"], ["먹었어요", "meogeosseoyo"], ["먹을 거예요", "meogeul geoyeyo"], ["먹습니다", "meokseumnida"], ["안 먹어요", "an meogeoyo"]]),
      V("하다", "hada", g("faire", "to do"), "A1", [["하다", "hada"], ["해요", "haeyo"], ["했어요", "haesseoyo"], ["할 거예요", "hal geoyeyo"], ["합니다", "hamnida"], ["안 해요", "an haeyo"]], { irregular: true }),
      V("보다", "boda", g("voir", "to see"), "A1", [["보다", "boda"], ["봐요", "bwayo"], ["봤어요", "bwasseoyo"], ["볼 거예요", "bol geoyeyo"], ["봅니다", "bomnida"], ["안 봐요", "an bwayo"]]),
      V("마시다", "masida", g("boire", "to drink"), "A1", [["마시다", "masida"], ["마셔요", "masyeoyo"], ["마셨어요", "masyeosseoyo"], ["마실 거예요", "masil geoyeyo"], ["마십니다", "masimnida"], ["안 마셔요", "an masyeoyo"]]),
      V("있다", "itda", g("avoir, y avoir, être (lieu)", "to have, there is, to be (place)"), "A1", [["있다", "itda"], ["있어요", "isseoyo"], ["있었어요", "isseosseoyo"], ["있을 거예요", "isseul geoyeyo"], ["있습니다", "isseumnida"], ["없어요", "eopseoyo"]], { irregular: true }),
    ],
  },
  readings: [
    { id: "ko-r1", level: "A1", title: "자기소개", t: "안녕하세요. 제 이름은 민지예요. 저는 서울에 살아요. 저는 대학생이에요. 저는 음악을 좋아해요. 주말에 친구하고 노래방에 가요.", r: "Annyeonghaseyo. Je ireumeun Minjiyeyo. Jeoneun Seoure sarayo. Jeoneun daehaksaengieyo. Jeoneun eumageul joahaeyo. Jumare chinguhago noraebange gayo.", tr: g("Bonjour. Je m'appelle Minji. J'habite à Séoul. Je suis étudiante. J'aime la musique. Le week-end, je vais au karaoké avec des amis.", "Hello. My name is Minji. I live in Seoul. I'm a university student. I like music. At weekends I go to karaoke with friends."),
      q: [q("Où va Minji le week-end ?", "Where does Minji go at weekends?", [["Au karaoké", "To karaoke"], ["Au cinéma", "To the cinema"], ["À la plage", "To the beach"]], 0)] },
    { id: "ko-r2", level: "A2", title: "시장에서", t: "어제 엄마하고 시장에 갔어요. 시장에는 사람이 많았어요. 우리는 과일하고 생선을 샀어요. 그리고 떡볶이를 먹었어요. 조금 매웠지만 정말 맛있었어요.", r: "Eoje eommahago sijange gasseoyo. Sijangeneun sarami manasseoyo. Urineun gwailhago saengseoneul sasseoyo. Geurigo tteokbokkireul meogeosseoyo. Jogeum maewotjiman jeongmal masisseosseoyo.", tr: g("Hier je suis allée au marché avec ma mère. Il y avait beaucoup de monde. Nous avons acheté des fruits et du poisson. Puis nous avons mangé des tteokbokki. C'était un peu épicé mais vraiment bon.", "Yesterday I went to the market with my mum. There were lots of people. We bought fruit and fish. Then we ate tteokbokki. It was a bit spicy but really tasty."),
      q: [q("Comment étaient les tteokbokki ?", "How were the tteokbokki?", [["Un peu épicés mais bons", "A bit spicy but tasty"], ["Froids", "Cold"], ["Sucrés", "Sweet"]], 0)] },
    { id: "ko-r3", level: "B1", title: "한글날", t: "10월 9일은 한글날이에요. 세종대왕은 백성들이 쉽게 글을 읽고 쓸 수 있도록 한글을 만들었어요. 한글은 과학적인 문자로 알려져 있어서, 외국인도 며칠 만에 읽는 법을 배울 수 있어요.", r: "Siwol gurireun Hangeullarieyo. Sejongdaewangeun baekseongdeuri swipge geureul ilgo sseul su itdorok Hangeureul mandeureosseoyo. Hangeureun gwahakjeogin munjaro allyeojyeo isseoseo, oegugindo myeochil mane ingneun beobeul baeul su isseoyo.", tr: g("Le 9 octobre est le jour du Hangeul. Le roi Sejong a créé le hangeul pour que le peuple puisse lire et écrire facilement. Le hangeul est connu comme une écriture scientifique : même les étrangers peuvent apprendre à le lire en quelques jours.", "October 9th is Hangul Day. King Sejong created Hangul so that ordinary people could read and write easily. Hangul is known as a scientific script, so even foreigners can learn to read it in a few days."),
      q: [q("Pourquoi Sejong a-t-il créé le hangeul ?", "Why did Sejong create Hangul?", [["Pour que le peuple sache lire facilement", "So ordinary people could read easily"], ["Pour les moines", "For monks"], ["Pour le commerce avec la Chine", "For trade with China"]], 0)] },
  ],
  culture: [
    { id: "ko-c1", level: "A1", icon: "🎂", title: g("L'âge", "Age"), body: g("<p>L'âge détermine le niveau de politesse. On demande souvent l'âge dès la rencontre pour savoir comment parler.</p>", "<p>Age determines politeness level. People often ask your age right away to know how to speak to you.</p>") },
    { id: "ko-c2", level: "A2", icon: "🥢", title: g("À table", "At the table"), body: g("<p>On attend que la personne la plus âgée commence. Riz et soupe se mangent à la cuillère, les accompagnements (<i>banchan</i>) aux baguettes.</p>", "<p>Wait for the eldest to start eating. Rice and soup are eaten with a spoon, side dishes (<i>banchan</i>) with chopsticks.</p>") },
    { id: "ko-c3", level: "B1", icon: "🌊", title: g("La vague coréenne", "The Korean Wave"), body: g("<p>Le <i>hallyu</i> (K-pop, séries, cinéma) a fait exploser l'apprentissage du coréen dans le monde.</p>", "<p>The <i>hallyu</i> (K-pop, dramas, film) has made Korean learning boom worldwide.</p>") },
  ],
};
