const { g, verb, ex, q } = require("./_helpers");
const P = ["ik", "jij", "hij / zij", "wij", "jullie", "zij"];
const V = (t, gl, lvl, f, o) => verb(P, t, gl, lvl, f, o);
module.exports = {
  replace: ["grammar", "readings"],
  note: g("Le néerlandais est parlé aux Pays-Bas, en Flandre (Belgique) et au Suriname. Attention au « g » guttural et à la diphtongue « ui ».", "Dutch is spoken in the Netherlands, Flanders (Belgium) and Suriname. Mind the guttural 'g' and the 'ui' diphthong."),
  grammar: [
    { id: "nl-lidwoord", level: "A1", icon: "⚥", title: g("de et het", "de and het"), body: g("<p>Deux articles définis : <b>de</b> (masculin/féminin, et tous les pluriels) et <b>het</b> (neutre, diminutifs en -je). Indéfini : <b>een</b>. <i>de man, het huis, het huisje, de huizen</i>.</p>", "<p>Two definite articles: <b>de</b> (common gender, and all plurals) and <b>het</b> (neuter, diminutives in -je). Indefinite: <b>een</b>. <i>de man, het huis, het huisje, de huizen</i>.</p>"), ex: [ex("Het meisje leest een boek.", "", "La fillette lit un livre.", "The girl reads a book.")] },
    { id: "nl-v2", level: "A1", icon: "2️⃣", title: g("Le verbe en 2e position", "Verb in second position"), body: g("<p>Dans la principale, le verbe conjugué est toujours 2<sup>e</sup> : <i>Morgen <b>ga</b> ik naar Amsterdam</i>. Dans la subordonnée, il va à la fin : <i>…omdat ik naar Amsterdam <b>ga</b></i>.</p>", "<p>In main clauses the finite verb is always second: <i>Morgen <b>ga</b> ik naar Amsterdam</i>. In subordinate clauses it goes last: <i>…omdat ik naar Amsterdam <b>ga</b></i>.</p>"), ex: [ex("Vandaag werk ik thuis.", "", "Aujourd'hui je travaille à la maison.", "Today I'm working from home.")] },
    { id: "nl-present", level: "A1", icon: "⚡", title: g("Le présent", "Present tense"), body: g("<p>Radical (ik werk), radical + t (jij/hij werkt), infinitif au pluriel (wij werken). Avec inversion, jij perd le -t : <i>Werk jij?</i></p>", "<p>Stem (ik werk), stem + t (jij/hij werkt), infinitive in the plural (wij werken). In inversion jij loses the -t: <i>Werk jij?</i></p>"), ex: [ex("Spreek jij Nederlands?", "", "Parles-tu néerlandais ?", "Do you speak Dutch?")] },
    { id: "nl-perfectum", level: "A2", icon: "⏪", title: g("Le passé composé (perfectum)", "Present perfect (perfectum)"), body: g("<p><b>hebben/zijn</b> + participe (ge-…-t/-d/-en) à la fin : <i>Ik heb gewerkt</i>, <i>Ik ben gegaan</i>. Règle « 't kofschip » : -t après t, k, f, s, ch, p.</p>", "<p><b>hebben/zijn</b> + participle (ge-…-t/-d/-en) at the end: <i>Ik heb gewerkt</i>, <i>Ik ben gegaan</i>. The ''t kofschip' rule: -t after t, k, f, s, ch, p.</p>"), ex: [ex("Gisteren heb ik gefietst.", "", "Hier j'ai fait du vélo.", "Yesterday I cycled.")] },
    { id: "nl-er", level: "B1", icon: "📍", title: g("Le petit mot « er »", "The little word 'er'"), body: g("<p><b>er</b> a plusieurs rôles : « il y a » (<i>Er is een probleem</i>), « y / en » (<i>Ik heb er twee</i>), avec préposition (<i>Ik denk erover</i>).</p>", "<p><b>er</b> has several uses: 'there is' (<i>Er is een probleem</i>), 'of them' (<i>Ik heb er twee</i>), with prepositions (<i>Ik denk erover</i>, I'm thinking about it).</p>"), ex: [ex("Er zijn veel fietsen in Utrecht.", "", "Il y a beaucoup de vélos à Utrecht.", "There are many bikes in Utrecht.")] },
    { id: "nl-scheidbaar", level: "B1", icon: "✂️", title: g("Verbes à particule séparable", "Separable verbs"), body: g("<p><i>opbellen</i> : <i>Ik bel je morgen <b>op</b></i>. Au participe : <i>opgebeld</i>.</p>", "<p><i>opbellen</i>: <i>Ik bel je morgen <b>op</b></i> (I'll call you tomorrow). Participle: <i>opgebeld</i>.</p>"), ex: [ex("De trein vertrekt om acht uur en komt om tien uur aan.", "", "Le train part à huit heures et arrive à dix heures.", "The train leaves at eight and arrives at ten.")] },
  ],
  conj: {
    tenses: [{ id: "present", fr: "Présent", en: "Present" }, { id: "imperfectum", fr: "Prétérit", en: "Simple past" }],
    verbs: [
      V("zijn", g("être", "to be"), "A1", { present: ["ben", "bent", "is", "zijn", "zijn", "zijn"], imperfectum: ["was", "was", "was", "waren", "waren", "waren"] }, { irregular: true }),
      V("hebben", g("avoir", "to have"), "A1", { present: ["heb", "hebt", "heeft", "hebben", "hebben", "hebben"], imperfectum: ["had", "had", "had", "hadden", "hadden", "hadden"] }, { irregular: true }),
      V("werken", g("travailler", "to work"), "A1", { present: ["werk", "werkt", "werkt", "werken", "werken", "werken"], imperfectum: ["werkte", "werkte", "werkte", "werkten", "werkten", "werkten"] }),
      V("gaan", g("aller", "to go"), "A1", { present: ["ga", "gaat", "gaat", "gaan", "gaan", "gaan"], imperfectum: ["ging", "ging", "ging", "gingen", "gingen", "gingen"] }, { irregular: true }),
      V("komen", g("venir", "to come"), "A1", { present: ["kom", "komt", "komt", "komen", "komen", "komen"], imperfectum: ["kwam", "kwam", "kwam", "kwamen", "kwamen", "kwamen"] }, { irregular: true }),
      V("kunnen", g("pouvoir", "can"), "A2", { present: ["kan", "kunt / kan", "kan", "kunnen", "kunnen", "kunnen"], imperfectum: ["kon", "kon", "kon", "konden", "konden", "konden"] }, { irregular: true }),
    ],
  },
  readings: [
    { id: "nl-r1", level: "A1", title: "Mijn fiets", t: "Ik heet Sanne en ik woon in Utrecht. Elke dag ga ik met de fiets naar mijn werk. Het is tien minuten. Als het regent, neem ik de bus. In het weekend fiets ik met vrienden langs de rivier.", tr: g("Je m'appelle Sanne et j'habite à Utrecht. Tous les jours, je vais au travail à vélo. C'est à dix minutes. Quand il pleut, je prends le bus. Le week-end, je fais du vélo avec des amis le long de la rivière.", "My name is Sanne and I live in Utrecht. Every day I cycle to work. It takes ten minutes. When it rains I take the bus. At weekends I cycle along the river with friends."),
      q: [q("Que fait Sanne quand il pleut ?", "What does Sanne do when it rains?", [["Elle prend le bus", "She takes the bus"], ["Elle reste chez elle", "She stays home"], ["Elle marche", "She walks"]], 0)] },
    { id: "nl-r2", level: "A2", title: "Koningsdag", t: "Op 27 april is het Koningsdag. Dan viert Nederland de verjaardag van de koning. Iedereen draagt oranje kleren. Op straat verkopen mensen oude spullen op de vrijmarkt en overal is muziek. Het is het grootste feest van het jaar.", tr: g("Le 27 avril, c'est le Jour du Roi. Les Pays-Bas fêtent l'anniversaire du roi. Tout le monde porte des vêtements orange. Dans la rue, les gens vendent de vieux objets au marché libre et il y a de la musique partout. C'est la plus grande fête de l'année.", "On 27 April it's King's Day. The Netherlands celebrates the king's birthday. Everyone wears orange. People sell old things at the street 'free market' and there's music everywhere. It's the biggest party of the year."),
      q: [q("Quelle couleur porte-t-on ?", "What colour do people wear?", [["Orange", "Orange"], ["Rouge", "Red"], ["Bleu", "Blue"]], 0)] },
  ],
  culture: [
    { id: "nl-c1", level: "A1", icon: "🚲", title: g("Le vélo", "Cycling"), body: g("<p>Il y a plus de vélos que d'habitants aux Pays-Bas. Les pistes cyclables sont partout ; attention en tant que piéton !</p>", "<p>There are more bikes than people in the Netherlands. Cycle lanes are everywhere — watch out as a pedestrian!</p>") },
    { id: "nl-c2", level: "A2", icon: "🗓️", title: g("L'agenda", "The diary"), body: g("<p>Les Néerlandais planifient tout, même les visites entre amis. Le franc-parler (<i>directheid</i>) est apprécié.</p>", "<p>The Dutch plan everything, even visits among friends. Directness (<i>directheid</i>) is valued.</p>") },
    { id: "nl-c3", level: "B1", icon: "🌊", title: g("Sous le niveau de la mer", "Below sea level"), body: g("<p>Environ un quart du pays est sous le niveau de la mer, protégé par des digues et des polders : « Dieu a créé le monde, les Néerlandais ont créé les Pays-Bas. »</p>", "<p>About a quarter of the country lies below sea level, protected by dykes and polders: 'God created the world, the Dutch created the Netherlands.'</p>") },
  ],
};
