const { g, verb, ex, q } = require("./_helpers");
const P = ["eu", "tu", "ele / ela / você", "nós", "vós", "eles / elas / vocês"];
const V = (t, gl, lvl, f, o) => verb(P, t, gl, lvl, f, o);
module.exports = {
  replace: ["grammar", "readings"],
  note: g("Le portugais s'écrit avec l'alphabet latin, des accents (á, â, ã, ç…) et des voyelles nasales (ão, ões). Les exemples suivent la norme européenne ; le Brésil diffère surtout à l'oral.", "Portuguese uses the Latin alphabet with accents (á, â, ã, ç…) and nasal vowels (ão, ões). Examples follow European Portuguese; Brazilian differs mainly in speech."),
  grammar: [
    { id: "pt-genero", level: "A1", icon: "⚥", title: g("Genre et articles", "Gender and articles"), body: g("<p>Masculin : <b>o / um</b> (souvent en -o) ; féminin : <b>a / uma</b> (souvent en -a). Pluriel : <b>os, as, uns, umas</b>. Les prépositions se contractent : <i>de + o = do</i>, <i>em + a = na</i>.</p>", "<p>Masculine: <b>o / um</b> (often ending in -o); feminine: <b>a / uma</b> (often -a). Plural: <b>os, as, uns, umas</b>. Prepositions contract: <i>de + o = do</i>, <i>em + a = na</i>.</p>"), ex: [ex("o livro e a casa", "", "le livre et la maison", "the book and the house"), ex("Estou na praia.", "", "Je suis à la plage.", "I'm at the beach.")] },
    { id: "pt-ser-estar", level: "A1", icon: "⚖️", title: g("Ser ou estar ?", "Ser or estar?"), body: g("<p><b>ser</b> : identité, caractéristiques durables, origine (<i>Sou português</i>). <b>estar</b> : état passager, lieu (<i>Estou cansado</i>, <i>Estou em Lisboa</i>).</p>", "<p><b>ser</b>: identity, lasting traits, origin (<i>Sou português</i>). <b>estar</b>: temporary states, location (<i>Estou cansado</i>, <i>Estou em Lisboa</i>).</p>"), ex: [ex("Ela é médica e está feliz.", "", "Elle est médecin et elle est heureuse.", "She is a doctor and she is happy.")] },
    { id: "pt-presente", level: "A1", icon: "⚡", title: g("Le présent (-ar, -er, -ir)", "Present tense (-ar, -er, -ir)"), body: g("<p>-ar : <i>falo, falas, fala, falamos, falais, falam</i>. -er : <i>como, comes, come…</i> -ir : <i>parto, partes, parte…</i></p>", "<p>-ar: <i>falo, falas, fala, falamos, falais, falam</i>. -er: <i>como, comes, come…</i> -ir: <i>parto, partes, parte…</i></p>"), ex: [ex("Nós falamos português.", "", "Nous parlons portugais.", "We speak Portuguese.")] },
    { id: "pt-negacao", level: "A1", icon: "🚫", title: g("La négation", "Negation"), body: g("<p><b>não</b> se place devant le verbe : <i>Não percebo</i> (je ne comprends pas). La double négation est normale : <i>Não vi ninguém</i>.</p>", "<p><b>não</b> goes before the verb: <i>Não percebo</i> (I don't understand). Double negation is normal: <i>Não vi ninguém</i> (I didn't see anyone).</p>"), ex: [ex("Não gosto de café.", "", "Je n'aime pas le café.", "I don't like coffee.")] },
    { id: "pt-preterito", level: "A2", icon: "⏪", title: g("Le passé simple (pretérito perfeito)", "Simple past (pretérito perfeito)"), body: g("<p>Pour une action terminée : <i>falei, falaste, falou, falámos, falastes, falaram</i>. Il s'emploie là où le français utilise le passé composé.</p>", "<p>For completed actions: <i>falei, falaste, falou, falámos, falastes, falaram</i>. Used where English uses the simple past.</p>"), ex: [ex("Ontem comi bacalhau.", "", "Hier j'ai mangé de la morue.", "Yesterday I ate salt cod.")] },
    { id: "pt-imperfeito", level: "B1", icon: "🎞️", title: g("L'imparfait", "The imperfect"), body: g("<p>Habitudes et descriptions passées : <i>falava, falavas, falava, falávamos…</i> <i>Quando era criança, brincava na rua.</i></p>", "<p>Past habits and descriptions: <i>falava, falavas, falava, falávamos…</i> <i>Quando era criança, brincava na rua</i> (As a child I used to play in the street).</p>"), ex: [ex("Quando era pequeno, vivia no Porto.", "", "Quand j'étais petit, je vivais à Porto.", "When I was little, I lived in Porto.")] },
    { id: "pt-pronomes", level: "B1", icon: "🔗", title: g("Les pronoms clitiques", "Clitic pronouns"), body: g("<p>En portugais européen, le pronom suit le verbe avec un trait d'union (<i>Vejo-o</i>), mais le précède après une négation ou certains mots (<i>Não o vejo</i>). Au Brésil, on le place souvent avant le verbe.</p>", "<p>In European Portuguese the pronoun follows the verb with a hyphen (<i>Vejo-o</i>), but precedes it after negation or certain words (<i>Não o vejo</i>). Brazilians usually place it before the verb.</p>"), ex: [ex("Dá-me o livro, por favor.", "", "Donne-moi le livre, s'il te plaît.", "Give me the book, please.")] },
    { id: "pt-conjuntivo", level: "B2", icon: "🌀", title: g("Le subjonctif (conjuntivo)", "The subjunctive (conjuntivo)"), body: g("<p>Après les expressions de souhait, de doute ou d'émotion : <i>Espero que venhas</i>. Il existe aussi un <b>futur du subjonctif</b>, propre au portugais : <i>Se puderes, liga-me</i>.</p>", "<p>After wishes, doubt or emotion: <i>Espero que venhas</i> (I hope you come). Portuguese also has a <b>future subjunctive</b>: <i>Se puderes, liga-me</i> (If you can, call me).</p>"), ex: [ex("Quando chegares, telefona-me.", "", "Quand tu arriveras, appelle-moi.", "When you arrive, call me.")] },
    { id: "pt-infinitivo", level: "C1", icon: "🎯", title: g("L'infinitif personnel", "The personal infinitive"), body: g("<p>Particularité du portugais : l'infinitif peut se conjuguer. <i>É melhor fazermos isto</i> (il vaut mieux que nous fassions cela).</p>", "<p>A Portuguese peculiarity: the infinitive can be inflected. <i>É melhor fazermos isto</i> (it's better for us to do this).</p>"), ex: [ex("Trouxe um livro para leres.", "", "J'ai apporté un livre pour que tu le lises.", "I brought a book for you to read.")] },
  ],
  conj: {
    tenses: [{ id: "presente", fr: "Présent", en: "Present" }, { id: "perfeito", fr: "Passé (pretérito perfeito)", en: "Simple past" }, { id: "futuro", fr: "Futur", en: "Future" }],
    verbs: [
      V("ser", g("être (permanent)", "to be (permanent)"), "A1", { presente: ["sou", "és", "é", "somos", "sois", "são"], perfeito: ["fui", "foste", "foi", "fomos", "fostes", "foram"], futuro: ["serei", "serás", "será", "seremos", "sereis", "serão"] }, { irregular: true }),
      V("estar", g("être (état, lieu)", "to be (state, place)"), "A1", { presente: ["estou", "estás", "está", "estamos", "estais", "estão"], perfeito: ["estive", "estiveste", "esteve", "estivemos", "estivestes", "estiveram"], futuro: ["estarei", "estarás", "estará", "estaremos", "estareis", "estarão"] }, { irregular: true }),
      V("ter", g("avoir", "to have"), "A1", { presente: ["tenho", "tens", "tem", "temos", "tendes", "têm"], perfeito: ["tive", "tiveste", "teve", "tivemos", "tivestes", "tiveram"], futuro: ["terei", "terás", "terá", "teremos", "tereis", "terão"] }, { irregular: true }),
      V("ir", g("aller", "to go"), "A1", { presente: ["vou", "vais", "vai", "vamos", "ides", "vão"], perfeito: ["fui", "foste", "foi", "fomos", "fostes", "foram"], futuro: ["irei", "irás", "irá", "iremos", "ireis", "irão"] }, { irregular: true }),
      V("falar", g("parler", "to speak"), "A1", { presente: ["falo", "falas", "fala", "falamos", "falais", "falam"], perfeito: ["falei", "falaste", "falou", "falámos", "falastes", "falaram"], futuro: ["falarei", "falarás", "falará", "falaremos", "falareis", "falarão"] }),
      V("comer", g("manger", "to eat"), "A1", { presente: ["como", "comes", "come", "comemos", "comeis", "comem"], perfeito: ["comi", "comeste", "comeu", "comemos", "comestes", "comeram"], futuro: ["comerei", "comerás", "comerá", "comeremos", "comereis", "comerão"] }),
      V("fazer", g("faire", "to do / make"), "A2", { presente: ["faço", "fazes", "faz", "fazemos", "fazeis", "fazem"], perfeito: ["fiz", "fizeste", "fez", "fizemos", "fizestes", "fizeram"], futuro: ["farei", "farás", "fará", "faremos", "fareis", "farão"] }, { irregular: true }),
      V("poder", g("pouvoir", "can"), "A2", { presente: ["posso", "podes", "pode", "podemos", "podeis", "podem"], perfeito: ["pude", "pudeste", "pôde", "pudemos", "pudestes", "puderam"], futuro: ["poderei", "poderás", "poderá", "poderemos", "podereis", "poderão"] }, { irregular: true }),
    ],
  },
  readings: [
    { id: "pt-r1", level: "A1", title: "O meu bairro", t: "Chamo-me Inês e moro em Lisboa. O meu bairro é pequeno e bonito. Há uma padaria, um café e um jardim. Todas as manhãs compro pão fresco e bebo um café na esplanada.", tr: g("Je m'appelle Inês et j'habite à Lisbonne. Mon quartier est petit et joli. Il y a une boulangerie, un café et un jardin. Tous les matins, j'achète du pain frais et je bois un café en terrasse.", "My name is Inês and I live in Lisbon. My neighbourhood is small and pretty. There's a bakery, a café and a garden. Every morning I buy fresh bread and drink a coffee on the terrace."),
      q: [q("Que fait Inês le matin ?", "What does Inês do in the morning?", [["Elle achète du pain et boit un café", "She buys bread and drinks a coffee"], ["Elle court au jardin", "She runs in the garden"], ["Elle travaille au café", "She works at the café"]], 0)] },
    { id: "pt-r2", level: "A2", title: "Férias no Algarve", t: "No verão passado fomos ao Algarve. Ficámos numa casa perto da praia. Durante o dia nadámos no mar e à noite jantámos peixe grelhado. No último dia fizemos um passeio de barco para ver as grutas.", tr: g("L'été dernier, nous sommes allés en Algarve. Nous avons logé dans une maison près de la plage. La journée, nous nagions dans la mer et le soir nous dînions de poisson grillé. Le dernier jour, nous avons fait une promenade en bateau pour voir les grottes.", "Last summer we went to the Algarve. We stayed in a house near the beach. During the day we swam in the sea and in the evening we had grilled fish. On the last day we took a boat trip to see the caves."),
      q: [q("Qu'ont-ils fait le dernier jour ?", "What did they do on the last day?", [["Une promenade en bateau", "A boat trip"], ["Du vélo", "Cycling"], ["Du shopping", "Shopping"]], 0)] },
    { id: "pt-r3", level: "B1", title: "O fado", t: "O fado é uma música tradicional portuguesa, muitas vezes melancólica. Canta a saudade, o amor e o mar. Nasceu nos bairros populares de Lisboa no século XIX e, em 2011, foi reconhecido pela UNESCO como património imaterial da humanidade.", tr: g("Le fado est une musique traditionnelle portugaise, souvent mélancolique. Il chante la saudade, l'amour et la mer. Il est né dans les quartiers populaires de Lisbonne au XIXe siècle et, en 2011, l'UNESCO l'a reconnu comme patrimoine immatériel de l'humanité.", "Fado is a traditional Portuguese music, often melancholic. It sings of saudade, love and the sea. It was born in Lisbon's working-class neighbourhoods in the 19th century and, in 2011, was recognised by UNESCO as intangible cultural heritage."),
      q: [q("Où est né le fado ?", "Where was fado born?", [["Dans les quartiers populaires de Lisbonne", "In Lisbon's working-class neighbourhoods"], ["Au Brésil", "In Brazil"], ["À Porto", "In Porto"]], 0)] },
    { id: "pt-r4", level: "B2", title: "A lusofonia", t: "O português é língua oficial em nove países e é falado por mais de duzentos e cinquenta milhões de pessoas. A maioria vive no Brasil, mas a língua está presente também em Angola, Moçambique, Cabo Verde e Timor-Leste. Apesar das diferenças de pronúncia e de vocabulário, os falantes compreendem-se sem grande dificuldade.", tr: g("Le portugais est langue officielle dans neuf pays et parlé par plus de deux cent cinquante millions de personnes. La plupart vivent au Brésil, mais la langue est aussi présente en Angola, au Mozambique, au Cap-Vert et au Timor oriental. Malgré les différences de prononciation et de vocabulaire, les locuteurs se comprennent sans grande difficulté.", "Portuguese is an official language in nine countries and is spoken by more than two hundred and fifty million people. Most live in Brazil, but the language is also present in Angola, Mozambique, Cape Verde and East Timor. Despite differences in pronunciation and vocabulary, speakers understand each other without much difficulty."),
      q: [q("Où vit la majorité des lusophones ?", "Where do most Portuguese speakers live?", [["Au Brésil", "In Brazil"], ["Au Portugal", "In Portugal"], ["En Angola", "In Angola"]], 0)] },
  ],
  culture: [
    { id: "pt-c1", level: "A1", icon: "☕", title: g("Le café", "Coffee"), body: g("<p>Au Portugal, on commande <i>uma bica</i> (Lisbonne) ou <i>um cimbalino</i> (Porto) pour un expresso. Le café est un rituel social quotidien.</p>", "<p>In Portugal you order <i>uma bica</i> (Lisbon) or <i>um cimbalino</i> (Porto) for an espresso. Coffee is a daily social ritual.</p>") },
    { id: "pt-c2", level: "A2", icon: "💙", title: g("La saudade", "Saudade"), body: g("<p>Mot réputé intraduisible : un mélange de nostalgie, de manque et d'espoir envers quelqu'un ou quelque chose d'absent.</p>", "<p>A word said to be untranslatable: a blend of nostalgia, longing and hope for someone or something absent.</p>") },
    { id: "pt-c3", level: "B1", icon: "🧭", title: g("Les Grandes Découvertes", "The Age of Discovery"), body: g("<p>Aux XVe et XVIe siècles, les navigateurs portugais (Vasco de Gama, Cabral) ouvrent la route maritime des Indes et atteignent le Brésil, ce qui explique la diffusion mondiale de la langue.</p>", "<p>In the 15th and 16th centuries, Portuguese navigators (Vasco da Gama, Cabral) opened the sea route to India and reached Brazil, which explains the language's worldwide spread.</p>") },
    { id: "pt-c4", level: "B2", icon: "🎭", title: g("Portugal et Brésil", "Portugal and Brazil"), body: g("<p>Au Brésil, on utilise <i>você</i> au lieu de <i>tu</i> dans une grande partie du pays, et certains mots diffèrent : <i>autocarro</i> (PT) / <i>ônibus</i> (BR), <i>comboio</i> / <i>trem</i>.</p>", "<p>In Brazil <i>você</i> replaces <i>tu</i> in much of the country, and some words differ: <i>autocarro</i> (PT) / <i>ônibus</i> (BR) for bus, <i>comboio</i> / <i>trem</i> for train.</p>") },
  ],
};
