const { g, verb, ex, q } = require("./_helpers");
const P = ["я", "ты", "он / она", "мы", "вы", "они"];
const V = (t, r, gl, lvl, f, o) => verb(P, t, gl, lvl, f, Object.assign({ r }, o));
const A = (c, name, sound, t, r, fr, en) => ({ c, final: "", name, sound, ex: { t, r, g: g(fr, en) } });
module.exports = {
  replace: ["grammar", "readings"],
  note: g("Le russe s'écrit en cyrillique. L'accent tonique est libre et change la prononciation des voyelles (о non accentué ≈ a) : écoutez chaque mot.", "Russian is written in Cyrillic. Stress is free and changes vowel sounds (unstressed о ≈ a): listen to every word."),
  alphabetNote: g("33 lettres. Certaines ressemblent au latin mais se lisent autrement : В = v, Н = n, Р = r, С = s, У = ou.", "33 letters. Some look Latin but read differently: В = v, Н = n, Р = r, С = s, У = oo."),
  alphabet: [
    A("А а", "a", "a", "мама", "mama", "maman", "mum"), A("Б б", "bé", "b", "брат", "brat", "frère", "brother"), A("В в", "vé", "v", "вода", "voda", "eau", "water"),
    A("Г г", "gué", "g", "город", "gorod", "ville", "city"), A("Д д", "dé", "d", "дом", "dom", "maison", "house"), A("Е е", "ié", "ye", "ехать", "yekhat'", "aller (en véhicule)", "to go (by vehicle)"),
    A("Ё ё", "io", "yo", "ёлка", "yolka", "sapin", "fir tree"), A("Ж ж", "jé", "zh", "жизнь", "zhizn'", "vie", "life"), A("З з", "zé", "z", "зима", "zima", "hiver", "winter"),
    A("И и", "i", "i", "имя", "imya", "prénom", "first name"), A("Й й", "i kratkoïé", "y", "май", "may", "mai", "May"), A("К к", "ka", "k", "кошка", "koshka", "chat", "cat"),
    A("Л л", "el", "l", "лето", "leto", "été", "summer"), A("М м", "em", "m", "мир", "mir", "paix / monde", "peace / world"), A("Н н", "en", "n", "нос", "nos", "nez", "nose"),
    A("О о", "o", "o", "окно", "okno", "fenêtre", "window"), A("П п", "pé", "p", "папа", "papa", "papa", "dad"), A("Р р", "er", "r (roulé)", "рука", "ruka", "main / bras", "hand / arm"),
    A("С с", "es", "s", "сок", "sok", "jus", "juice"), A("Т т", "té", "t", "там", "tam", "là-bas", "there"), A("У у", "ou", "u", "утро", "utro", "matin", "morning"),
    A("Ф ф", "ef", "f", "фото", "foto", "photo", "photo"), A("Х х", "kha", "kh", "хлеб", "khleb", "pain", "bread"), A("Ц ц", "tsé", "ts", "цвет", "tsvet", "couleur", "colour"),
    A("Ч ч", "tché", "ch", "чай", "chay", "thé", "tea"), A("Ш ш", "cha", "sh", "школа", "shkola", "école", "school"), A("Щ щ", "chtcha", "shch", "щи", "shchi", "soupe de chou", "cabbage soup"),
    A("Ъ ъ", "signe dur", "—", "объём", "ob'yom", "volume", "volume"), A("Ы ы", "y", "ɨ", "мы", "my", "nous", "we"), A("Ь ь", "signe mou", "(mouillure)", "день", "den'", "jour", "day"),
    A("Э э", "è", "e", "это", "eto", "c'est / ceci", "this is"), A("Ю ю", "iou", "yu", "юг", "yug", "sud", "south"), A("Я я", "ia", "ya", "яблоко", "yabloko", "pomme", "apple"),
  ],
  grammar: [
    { id: "ru-articles", level: "A1", icon: "🚫", title: g("Pas d'articles, pas de « être » au présent", "No articles, no 'to be' in the present"), body: g("<p>Le russe n'a pas d'articles et omet le verbe « être » au présent : <i>Я студент</i> = je suis étudiant. À l'écrit, un tiret remplace parfois le verbe : <i>Москва — столица России</i>.</p>", "<p>Russian has no articles and drops 'to be' in the present: <i>Я студент</i> = I am a student. In writing a dash sometimes stands for the verb: <i>Москва — столица России</i>.</p>"), ex: [ex("Это мой дом.", "Eto moy dom.", "C'est ma maison.", "This is my house.")] },
    { id: "ru-genre", level: "A1", icon: "⚥", title: g("Les trois genres", "The three genders"), body: g("<p>Masculin : consonne ou -й (<i>стол</i>). Féminin : -а / -я (<i>мама</i>). Neutre : -о / -е (<i>окно</i>). Les noms en -ь peuvent être masculins ou féminins.</p>", "<p>Masculine: consonant or -й (<i>стол</i>). Feminine: -а / -я (<i>мама</i>). Neuter: -о / -е (<i>окно</i>). Nouns in -ь can be masculine or feminine.</p>"), ex: [ex("новый стол, новая книга, новое окно", "novyy stol, novaya kniga, novoye okno", "une nouvelle table, un nouveau livre, une nouvelle fenêtre", "a new table, a new book, a new window")] },
    { id: "ru-present", level: "A1", icon: "⚡", title: g("Le présent : deux conjugaisons", "Present tense: two conjugations"), body: g("<p>1<sup>re</sup> conjugaison (-ешь) : <i>читаю, читаешь, читает…</i> 2<sup>e</sup> conjugaison (-ишь) : <i>говорю, говоришь, говорит…</i></p>", "<p>1st conjugation (-ешь): <i>читаю, читаешь, читает…</i> 2nd conjugation (-ишь): <i>говорю, говоришь, говорит…</i></p>"), ex: [ex("Я читаю книгу.", "Ya chitayu knigu.", "Je lis un livre.", "I'm reading a book.")] },
    { id: "ru-cas", level: "A2", icon: "🧩", title: g("Les six cas", "The six cases"), body: g("<p>Nominatif (sujet), accusatif (COD), génitif (possession, quantité, négation), datif (à qui), instrumental (avec, par), prépositionnel (où, de quoi). <i>книга → книгу → книги → книге → книгой</i>.</p>", "<p>Nominative (subject), accusative (object), genitive (possession, quantity, negation), dative (to whom), instrumental (with, by), prepositional (where, about). <i>книга → книгу → книги → книге → книгой</i>.</p>"), ex: [ex("Я живу в Москве.", "Ya zhivu v Moskve.", "J'habite à Moscou.", "I live in Moscow."), ex("У меня нет машины.", "U menya net mashiny.", "Je n'ai pas de voiture.", "I don't have a car.")] },
    { id: "ru-passe", level: "A2", icon: "⏪", title: g("Le passé", "The past tense"), body: g("<p>Le passé s'accorde en genre et en nombre, pas en personne : <i>он читал, она читала, оно читало, они читали</i>.</p>", "<p>The past agrees in gender and number, not person: <i>он читал, она читала, оно читало, они читали</i>.</p>"), ex: [ex("Вчера она работала.", "Vchera ona rabotala.", "Hier, elle a travaillé.", "Yesterday she worked.")] },
    { id: "ru-aspect", level: "B1", icon: "🔁", title: g("L'aspect : imperfectif / perfectif", "Aspect: imperfective / perfective"), body: g("<p>Presque chaque verbe a deux formes. Imperfectif : action en cours, répétée (<i>писать</i>). Perfectif : action achevée, résultat (<i>написать</i>). Le perfectif conjugué au « présent » exprime le futur : <i>Я напишу</i> = j'écrirai.</p>", "<p>Almost every verb has two forms. Imperfective: ongoing or repeated action (<i>писать</i>). Perfective: completed action, result (<i>написать</i>). A perfective in 'present' form means future: <i>Я напишу</i> = I will write.</p>"), ex: [ex("Я писал письмо весь день и наконец написал его.", "Ya pisal pis'mo ves' den' i nakonets napisal yego.", "J'ai écrit la lettre toute la journée et je l'ai enfin terminée.", "I was writing the letter all day and finally finished it.")] },
    { id: "ru-mouvement", level: "B1", icon: "🚶", title: g("Les verbes de mouvement", "Verbs of motion"), body: g("<p>À pied ou en véhicule, un sens ou aller-retour : <i>идти / ходить</i> (à pied), <i>ехать / ездить</i> (en véhicule). <i>Я иду в школу</i> (j'y vais maintenant) ; <i>Я хожу в школу</i> (j'y vais régulièrement).</p>", "<p>On foot or by vehicle, one direction or round trips: <i>идти / ходить</i> (on foot), <i>ехать / ездить</i> (by vehicle). <i>Я иду в школу</i> (I'm going now); <i>Я хожу в школу</i> (I go regularly).</p>"), ex: [ex("Завтра мы едем в Петербург.", "Zavtra my yedem v Peterburg.", "Demain nous allons à Saint-Pétersbourg.", "Tomorrow we're going to St Petersburg.")] },
    { id: "ru-nombres", level: "B2", icon: "🔢", title: g("Les nombres et les cas", "Numbers and cases"), body: g("<p>Après 1 : nominatif (<i>один год</i>) ; après 2, 3, 4 : génitif singulier (<i>два года</i>) ; après 5 et plus : génitif pluriel (<i>пять лет</i>).</p>", "<p>After 1: nominative (<i>один год</i>); after 2, 3, 4: genitive singular (<i>два года</i>); after 5+: genitive plural (<i>пять лет</i>).</p>"), ex: [ex("Мне двадцать два года.", "Mne dvadtsat' dva goda.", "J'ai vingt-deux ans.", "I'm twenty-two.")] },
  ],
  conj: {
    tenses: [{ id: "present", fr: "Présent", en: "Present" }, { id: "futur", fr: "Futur (perfectif)", en: "Future (perfective)" }],
    verbs: [
      V("читать", "chitat'", g("lire", "to read"), "A1", { present: [["читаю", "chitayu"], ["читаешь", "chitayesh'"], ["читает", "chitayet"], ["читаем", "chitayem"], ["читаете", "chitayete"], ["читают", "chitayut"]], futur: [["прочитаю", "prochitayu"], ["прочитаешь", "prochitayesh'"], ["прочитает", "prochitayet"], ["прочитаем", "prochitayem"], ["прочитаете", "prochitayete"], ["прочитают", "prochitayut"]] }),
      V("говорить", "govorit'", g("parler", "to speak"), "A1", { present: [["говорю", "govoryu"], ["говоришь", "govorish'"], ["говорит", "govorit"], ["говорим", "govorim"], ["говорите", "govorite"], ["говорят", "govoryat"]], futur: [["скажу", "skazhu"], ["скажешь", "skazhesh'"], ["скажет", "skazhet"], ["скажем", "skazhem"], ["скажете", "skazhete"], ["скажут", "skazhut"]] }, { irregular: true }),
      V("жить", "zhit'", g("vivre", "to live"), "A1", { present: [["живу", "zhivu"], ["живёшь", "zhivyosh'"], ["живёт", "zhivyot"], ["живём", "zhivyom"], ["живёте", "zhivyote"], ["живут", "zhivut"]] }, { irregular: true }),
      V("идти", "idti", g("aller (à pied)", "to go (on foot)"), "A1", { present: [["иду", "idu"], ["идёшь", "idyosh'"], ["идёт", "idyot"], ["идём", "idyom"], ["идёте", "idyote"], ["идут", "idut"]], futur: [["пойду", "poydu"], ["пойдёшь", "poydyosh'"], ["пойдёт", "poydyot"], ["пойдём", "poydyom"], ["пойдёте", "poydyote"], ["пойдут", "poydut"]] }, { irregular: true }),
      V("хотеть", "khotet'", g("vouloir", "to want"), "A1", { present: [["хочу", "khochu"], ["хочешь", "khochesh'"], ["хочет", "khochet"], ["хотим", "khotim"], ["хотите", "khotite"], ["хотят", "khotyat"]] }, { irregular: true }),
      V("мочь", "moch'", g("pouvoir", "can"), "A2", { present: [["могу", "mogu"], ["можешь", "mozhesh'"], ["может", "mozhet"], ["можем", "mozhem"], ["можете", "mozhete"], ["могут", "mogut"]] }, { irregular: true }),
      V("писать", "pisat'", g("écrire", "to write"), "A2", { present: [["пишу", "pishu"], ["пишешь", "pishesh'"], ["пишет", "pishet"], ["пишем", "pishem"], ["пишете", "pishete"], ["пишут", "pishut"]], futur: [["напишу", "napishu"], ["напишешь", "napishesh'"], ["напишет", "napishet"], ["напишем", "napishem"], ["напишете", "napishete"], ["напишут", "napishut"]] }),
    ],
  },
  readings: [
    { id: "ru-r1", level: "A1", title: "Моя семья", t: "Меня зовут Анна. Я живу в Москве. У меня есть брат и сестра. Мой брат врач, а сестра студентка. Вечером мы пьём чай и разговариваем.", r: "Menya zovut Anna. Ya zhivu v Moskve. U menya yest' brat i sestra. Moy brat vrach, a sestra studentka. Vecherom my p'yom chay i razgovarivayem.", tr: g("Je m'appelle Anna. J'habite à Moscou. J'ai un frère et une sœur. Mon frère est médecin et ma sœur est étudiante. Le soir, nous buvons du thé et nous discutons.", "My name is Anna. I live in Moscow. I have a brother and a sister. My brother is a doctor and my sister is a student. In the evening we drink tea and talk."),
      q: [q("Que fait le frère d'Anna ?", "What does Anna's brother do?", [["Il est médecin", "He's a doctor"], ["Il est étudiant", "He's a student"], ["Il est professeur", "He's a teacher"]], 0)] },
    { id: "ru-r2", level: "A2", title: "Выходные на даче", t: "В субботу мы поехали на дачу. Там мы работали в саду, собирали ягоды и купались в реке. Вечером папа приготовил шашлык. Мы вернулись в город в воскресенье поздно вечером.", r: "V subbotu my poyekhali na dachu. Tam my rabotali v sadu, sobirali yagody i kupalis' v reke. Vecherom papa prigotovil shashlyk. My vernulis' v gorod v voskresen'ye pozdno vecherom.", tr: g("Samedi, nous sommes allés à la datcha. Là-bas, nous avons travaillé au jardin, cueilli des baies et nous nous sommes baignés dans la rivière. Le soir, papa a préparé des brochettes. Nous sommes rentrés en ville dimanche tard le soir.", "On Saturday we went to the dacha. There we worked in the garden, picked berries and swam in the river. In the evening dad made shashlik. We returned to the city late on Sunday evening."),
      q: [q("Qu'a préparé papa ?", "What did dad cook?", [["Des brochettes (chachlik)", "Shashlik (skewers)"], ["Une soupe", "A soup"], ["Des crêpes", "Pancakes"]], 0)] },
    { id: "ru-r3", level: "B1", title: "Транссибирская магистраль", t: "Транссибирская магистраль — самая длинная железная дорога в мире. Она соединяет Москву и Владивосток. Поезд идёт почти неделю и пересекает восемь часовых поясов. Пассажиры читают, играют в карты и пьют чай из стаканов в подстаканниках.", r: "Transsibirskaya magistral' — samaya dlinnaya zheleznaya doroga v mire. Ona soyedinyayet Moskvu i Vladivostok. Poyezd idyot pochti nedelyu i peresekayet vosem' chasovykh poyasov. Passazhiry chitayut, igrayut v karty i p'yut chay iz stakanov v podstakannikakh.", tr: g("Le Transsibérien est la plus longue voie ferrée du monde. Il relie Moscou à Vladivostok. Le train roule presque une semaine et traverse huit fuseaux horaires. Les passagers lisent, jouent aux cartes et boivent du thé dans des verres à porte-verre.", "The Trans-Siberian Railway is the longest railway in the world. It links Moscow and Vladivostok. The train runs for almost a week and crosses eight time zones. Passengers read, play cards and drink tea from glasses in metal holders."),
      q: [q("Combien de fuseaux horaires traverse le train ?", "How many time zones does the train cross?", [["Huit", "Eight"], ["Trois", "Three"], ["Douze", "Twelve"]], 0)] },
  ],
  culture: [
    { id: "ru-c1", level: "A1", icon: "🫖", title: g("Le thé", "Tea"), body: g("<p>On boit le thé toute la journée, souvent avec de la confiture (<i>варенье</i>) ou des biscuits. Le samovar reste un symbole d'hospitalité.</p>", "<p>Tea is drunk all day, often with jam (<i>варенье</i>) or biscuits. The samovar remains a symbol of hospitality.</p>") },
    { id: "ru-c2", level: "A2", icon: "👤", title: g("Prénom et patronyme", "First name and patronymic"), body: g("<p>Pour s'adresser poliment à quelqu'un, on utilise le prénom suivi du patronyme : <i>Иван Петрович</i> (Ivan, fils de Piotr), <i>Анна Сергеевна</i>.</p>", "<p>To address someone politely you use first name plus patronymic: <i>Иван Петрович</i> (Ivan, son of Pyotr), <i>Анна Сергеевна</i>.</p>") },
    { id: "ru-c3", level: "B1", icon: "📚", title: g("La littérature", "Literature"), body: g("<p>Pouchkine est considéré comme le père de la langue littéraire moderne. Tolstoï, Dostoïevski, Tchekhov et Boulgakov sont lus dans le monde entier.</p>", "<p>Pushkin is considered the father of the modern literary language. Tolstoy, Dostoevsky, Chekhov and Bulgakov are read worldwide.</p>") },
  ],
};
