/*!
 * Interface strings of the app, in the account's base language.
 * fr + en are inline (French = reference, English = fallback for every base
 * language); other languages live in /course/i18n/<code>.js and are loaded on
 * demand with I18N.load(code). Missing keys fall back to English, then French.
 */
(function () {
  var D = {};
  // Base languages that have a full UI translation file in /course/i18n/.
  var AVAILABLE = ["fr", "en", "es", "it", "pt", "de", "nl", "sv", "nb", "da", "fi", "pl", "cs", "ro", "hu", "el", "ru", "uk", "tr", "ar", "he", "hi", "zh", "ja", "ko", "vi", "id", "sw", "ga", "cy", "ht", "eo", "la"];
  var RTL = { ar: 1, he: 1 };

  D.fr = {
    kids_title: "Mode enfant", kids_lead: "Une version simple et colorée pour les enfants : histoires illustrées, jeux d'images, imagier et autocollants à gagner. Pour revenir au mode adulte, il faudra répondre à une petite question de calcul.", kids_go: "Passer en mode enfant", mode_label: "Mode", mode_adult: "Adulte", mode_kids: "Enfant", mode_to_kids: "Mode enfant", mode_to_adult: "Mode adulte", gate_title: "Question pour les grands", gate_lead: "Pour revenir au mode adulte, réponds à ce calcul :", gate_ok: "Valider", gate_cancel: "Annuler",
    invoices_title: "Mes factures", invoices_lead: "Tes factures Premium, au format PDF.",
    data_title: "Mes données", data_lead: "Tu peux télécharger tout ce que l'application enregistre sur toi, déconnecter tous tes appareils ou supprimer définitivement ton compte.", data_export: "Télécharger mes données", logout_all: "Déconnecter tous les appareils", delete_account: "Supprimer mon compte", delete_lead: "La suppression efface ton compte, ta progression et tes idées. Les factures sont conservées pour la comptabilité, sans lien avec ton compte. Confirme avec ton mot de passe.", delete_pw_ph: "Ton mot de passe", delete_confirm: "Supprimer définitivement ton compte ? Cette action est irréversible.", wrong_password: "Mot de passe incorrect.", email_unverified: "Adresse email non confirmée : clique sur le lien reçu par email.",
    sub_btn: "S'abonner", sub_no_commit: "Sans engagement, annulable à tout moment", sub_no_ads: "Aucune publicité, jamais", sub_canceled: "Paiement annulé.", sub_success: "Paiement reçu, merci ! Ton accès premium est actif.", sub_redirect: "Redirection…", sub_unavailable: "Le paiement n'est pas encore disponible.",
    load_error: "Impossible de charger ce module.", loading: "Chargement…",
    learn_lang: "Apprendre : {lang}", modules: "Modules", go_premium: "Premium", speaking: "Lecture audio…", listen: "Écouter",
    tts_unsupported: "L'audio n'est pas disponible sur ce navigateur.", tts_no_voice: "Aucune voix « {lang} » installée sur cet appareil : l'audio utilise la voix par défaut.", tts_approx: "Voix approchée : aucune voix native n'existe pour cette langue sur cet appareil.",
    gloss_fallback: "Traduction indisponible dans ta langue de base : langue affichée à la place.",
    premium_only: "Réservé à Premium", premium_unlock: "passe à Premium pour le débloquer.", premium_title: "Premium", premium_sub: "Tout ce qu'il faut pour aller jusqu'au bout, dans les 39 langues.", premium_tools: "Outils Premium",
    "feat_levels-c": "Niveaux C1 et C2 (mots, leçons, examens)", "feat_lessons-unlimited": "Leçons illimitées", "feat_srs-advanced": "Révision SRS avancée (SM-2, prévisions, sans limite)", "feat_pronunciation-ai": "Prononciation avec reconnaissance vocale et score", "feat_stats-advanced": "Statistiques avancées", "feat_progress-detailed": "Progression détaillée mot par mot", "feat_certificates": "Certificats de niveau", "feat_badges": "Badges et succès", "feat_offline": "Mode hors-ligne", "feat_custom-words": "Mots personnels illimités", "feat_exam": "Examens blancs par niveau", "feat_export": "Export de la progression (CSV)", "feat_exercices-avances": "Exercices avancés (écrit, dictée, textes à trous, ordre, conjugaison)", "feat_lecons-avancees": "Leçons avancées (B1 et au-delà)", "feat_feedback-avance": "Feedback avancé (explications, analyse des erreurs)",
    mod_hub: "Accueil", mod_vocabulaire: "Vocabulaire", mod_phrases: "Phrases utiles", mod_grammaire: "Grammaire", mod_conjugaison: "Conjugaison", mod_alphabet: "Alphabet", mod_lecture: "Lecture", mod_ecoute: "Compréhension orale", mod_exercices: "Exercices", mod_revision: "Révision", mod_prononciation: "Prononciation", mod_culture: "Culture", mod_examen: "Examens", mod_stats: "Statistiques", mod_badges: "Badges", mod_certificat: "Certificats", mod_dictionnaire: "Dictionnaire", mod_profil: "Profil", mod_levels: "Niveau",
    desc_vocabulaire: "Tous les mots, par thème et par niveau", desc_phrases: "Les phrases du quotidien, avec audio", desc_grammaire: "Les règles essentielles, expliquées", desc_conjugaison: "Tableaux et entraînement", desc_alphabet: "L'écriture, lettre par lettre", desc_lecture: "Textes par niveau, avec questions", desc_ecoute: "Écoute, dictée, textes audio", desc_exercices: "QCM, écrit, trous, ordre des mots…", desc_revision: "Répétition espacée", desc_prononciation: "Écoute et répète", desc_culture: "Usages, histoire, repères", desc_examen: "Teste ton niveau A1 → C2", desc_stats: "Ta progression en chiffres", desc_badges: "Tes succès", desc_certificat: "Certificats imprimables", desc_dictionnaire: "Rechercher et ajouter des mots", desc_profil: "Réglages et audio",
    level: "Niveau", level_A1: "Débutant", level_A2: "Élémentaire", level_B1: "Intermédiaire", level_B2: "Intermédiaire avancé", level_C1: "Avancé", level_C2: "Maîtrise",
    all_levels: "Tous", all_themes: "Tous les thèmes", theme: "Thème", sort: "Trier", filter: "Filtrer", search: "Rechercher…",
    sort_theme: "Par thème", sort_level: "Par niveau", sort_alpha: "A → Z", sort_learn: "À apprendre d'abord",
    only_all: "Tous les mots", only_new: "Jamais vus", only_known: "Déjà sus",
    hub_intro: "Ton parcours en {lang} : vocabulaire, grammaire, lecture, écoute et exercices, du niveau A1 au C2.",
    xp: "points XP", streak_days: "jours de suite", words_known: "mots sus", accuracy: "réussite", answers: "réponses",
    reviews_due: "{n} mots à réviser aujourd'hui", review_now: "Réviser", word_of_day: "Mot du jour", cefr_levels: "Niveaux CECRL", explore: "Explorer",
    n_words: "{n} mots", n_known: "{n} sus", n_shown: "{n} affichés sur {total}", n_texts: "{n} textes", n_questions: "{n} questions",
    vocab_sub: "{n} mots, chacun avec son niveau CECRL. Touche un mot pour voir l'exemple.", show_more: "Afficher plus", no_results: "Aucun résultat.",
    locked_levels: "{n} mots de niveau {levels} sont réservés à Premium.", plural: "Pluriel", mine: "perso", known: "Su", in_review: "En révision", add_review: "Ajouter à la révision", added_review: "Ajouté à la révision", added_n: "{n} mots ajoutés à la révision", my_words: "Mes mots",
    phrases_sub: "Les phrases dont tu as besoin au quotidien, chacune avec l'audio.", grammar_sub: "Les règles de base du {lang}, avec exemples audio.", pronunciation_rules: "Prononciation",
    conj_sub: "Choisis un verbe pour voir ses formes, avec l'audio.", irregular: "irrégulier", practice: "S'entraîner",
    alphabet_sub: "Touche une lettre pour l'entendre et voir un exemple.", sound: "son",
    reading_sub: "Des textes classés par niveau : écoute-les, affiche la traduction, réponds aux questions.", listen_text: "Écouter le texte", show_text: "Afficher le texte", show_translation: "Traduction",
    listening_sub: "Entraîne ton oreille : écoute d'abord, lis ensuite.", listen_texts: "Textes à écouter",
    exercises_sub: "Choisis un niveau, un thème et un type d'exercice.",
    mode_mcq: "QCM", mode_mcq_d: "Choisis la bonne traduction", mode_reverse: "Traduction inverse", mode_reverse_d: "Trouve le mot à partir du sens", mode_listen: "Écoute", mode_listen_d: "Écoute et choisis le sens", mode_write: "Écrit", mode_write_d: "Tape le mot (clavier virtuel)", mode_dictation: "Dictée", mode_dictation_d: "Écris ce que tu entends", mode_cloze: "Textes à trous", mode_cloze_d: "Complète la phrase", mode_order: "Ordre des mots", mode_order_d: "Remets la phrase dans l'ordre", mode_conj: "Conjugaison", mode_conj_d: "Choisis la bonne forme", mode_mix: "Mélange", mode_mix_d: "Un peu de tout",
    quit: "Quitter", check: "Vérifier", continue: "Continuer", correct: "Correct !", wrong: "Pas tout à fait…", answer_was: "Réponse", example: "Exemple", similarity: "Ta réponse est proche à {n} %.", feedback_locked: "Explications détaillées avec le feedback avancé (Premium).",
    quiz_done: "Série terminée", score_line: "{ok}/{total} bonnes réponses ({pct} %) · +{xp} XP", again: "Recommencer", back: "Retour", review_errors: "Tes erreurs", you_said: "ta réponse", reset: "Effacer",
    srs_adv_sub: "Algorithme SM-2 : chaque mot revient juste avant que tu l'oublies.", srs_free_sub: "Répétition espacée par boîtes, {n} révisions par jour.", due_now: "à réviser", in_srs: "en révision", left_today: "restantes aujourd'hui",
    srs_cap_reached: "Limite quotidienne atteinte. Premium : révisions illimitées.", nothing_due: "Rien à réviser pour l'instant.", learn_new: "Ajouter de nouveaux mots", forecast: "Prévisions sur 7 jours", today: "Aujourd'hui",
    review_done: "Révision terminée !", show_answer: "Voir la réponse", grade_again: "À revoir", grade_hard: "Difficile", grade_good: "Bien", grade_easy: "Facile",
    pron_sub_ai: "Écoute, puis enregistre-toi : ta prononciation est comparée au modèle et notée.", pron_sub_free: "Écoute et répète à voix haute.", sr_unsupported: "La reconnaissance vocale n'est pas disponible sur ce navigateur (essaie Chrome ou Safari).", record: "Parler", listening: "Je t'écoute…", heard: "entendu", pron_great: "Excellent !", pron_ok: "Pas mal, encore un essai ?", pron_retry: "Réessaie en articulant.", sr_error: "Micro indisponible",
    culture_sub: "Usages, histoire et repères pour comprendre le monde du {lang}.",
    lesson: "Leçon", lesson_d: "8 nouveaux mots, puis un quiz de 10 questions.", start_lesson: "Commencer la leçon", lessons_left: "{n} leçons gratuites restantes aujourd'hui", lessons_cap: "Tu as fait tes 3 leçons gratuites du jour.", lesson_done: "Leçon terminée !", new_word: "Nouveau mot", words_of_level: "Mots du niveau {level}",
    exam_d: "20 questions. 80 % pour réussir et obtenir le certificat.", exam_best: "Meilleur score : {n} %", take_exam: "Passer l'examen", exam_sub: "Un examen par niveau : 20 questions, réussite à 80 %.", not_taken: "Pas encore passé", exam_passed: "Niveau {level} validé !", exam_failed: "Pas encore : il faut 80 %.", not_enough: "Pas assez de mots à ce niveau.",
    stats_sub: "Ta progression dans cette langue.", activity_30: "Activité (30 jours)", by_level: "Par niveau", by_theme: "Par thème (points faibles d'abord)", hardest_words: "Mots les plus difficiles",
    badges_sub: "{n} badges sur {total}.", earned_on: "obtenu le {d}", badge_new: "Nouveau badge : {name}",
    badge_first: "Premier pas", badge_first_d: "Répondre à une première question", badge_lesson1: "Première leçon", badge_lesson1_d: "Terminer une leçon", badge_lesson10: "Assidu", badge_lesson10_d: "Terminer 10 leçons", badge_words50: "50 mots", badge_words50_d: "Connaître 50 mots", badge_words250: "250 mots", badge_words250_d: "Connaître 250 mots", badge_words1000: "1000 mots", badge_words1000_d: "Connaître 1000 mots", badge_streak3: "Lancé", badge_streak3_d: "3 jours de suite", badge_streak7: "Une semaine", badge_streak7_d: "7 jours de suite", badge_streak30: "Un mois", badge_streak30_d: "30 jours de suite", badge_xp1000: "1000 XP", badge_xp1000_d: "Gagner 1000 XP", badge_perfect: "Sans faute", badge_perfect_d: "Une série parfaite", badge_reviewer: "Mémoire d'éléphant", badge_reviewer_d: "100 mots en révision", badge_examA: "Niveau A", badge_examA_d: "Réussir un examen A1 ou A2", badge_examB: "Niveau B", badge_examB_d: "Réussir un examen B1 ou B2", badge_examC: "Niveau C", badge_examC_d: "Réussir un examen C1 ou C2", badge_speaker: "Orateur", badge_speaker_d: "10 prononciations réussies",
    no_cert: "Pas encore de certificat", no_cert_d: "Réussis un examen de niveau (80 %) pour obtenir ton certificat.", print: "Imprimer", cert_title: "Certificat de réussite", cert_attests: "Ce certificat atteste que", cert_body: "a validé le niveau {level} ({label}) du CECRL en {lang}, avec un score de {score} %.", cert_date: "Délivré le {d}", learner: "Apprenant·e",
    dict_sub: "Cherche un mot, une phrase ou une règle — ou ajoute tes propres mots.", word_in: "Mot en {lang}", romanization: "Prononciation / romanisation", translation: "Traduction", word_required: "Le mot et sa traduction sont obligatoires.",
    sr_fallback: "Ce navigateur ne propose pas la reconnaissance vocale : utilise « Enregistrer et comparer » — tu entends le modèle puis ta voix, avec les deux ondes côte à côte.", rec_unsupported: "L'enregistrement audio n'est pas disponible ici : écoute et répète à voix haute.", rec_compare: "Enregistrer et comparer", rec_stop: "Arrêter", rec_me: "Ma voix", rec_model: "Modèle", rec_self: "Comment c'était ?", rec_good: "Bien", rec_again: "À retravailler", mic_denied: "Micro refusé ou indisponible : autorise-le dans ton navigateur.",
    progress: "Progression", progress_text: "{kind} {i} sur {n} ({pct} %)", progress_question: "Question", progress_step: "Étape",
    legal_notice: "Mentions légales", privacy_policy: "Confidentialité",
    sp_title: "Tout Pap’pote, sans limite", sp_lead: "Les 39 langues restent gratuites jusqu'au niveau B2. Premium débloque tout le reste : niveaux C1-C2, leçons et révisions illimitées, exercices avancés, examens, certificats…",
    sp_r1: "Sans engagement, annulable en un clic", sp_r2: "Paiement sécurisé par Stripe", sp_r3: "Aucune publicité, jamais",
    sp_compare: "Gratuit ou Premium : ce qui est inclus", sp_feature: "Fonctionnalité", sp_free: "Gratuit", sp_yes: "inclus", sp_no: "non inclus", sp_faq: "Questions fréquentes",
    sp_q1: "Puis-je annuler quand je veux ?", sp_a1: "Oui, sans engagement : tu annules depuis le lien reçu par email ou le portail Stripe, et tu gardes Premium jusqu'à la fin de la période déjà payée.",
    sp_q2: "Que se passe-t-il si j'arrête Premium ?", sp_a2: "Tu repasses en gratuit sans rien perdre : ta progression, tes mots et tes badges restent dans ton compte. Seuls les contenus Premium redeviennent verrouillés.",
    sp_q3: "Le paiement est-il sécurisé ?", sp_a3: "Le paiement se fait sur la page sécurisée de Stripe : Pap’pote ne voit et ne stocke jamais ta carte bancaire. Une facture t'est envoyée par email.",
    sp_q4: "Et si un ami m'a invité ?", sp_a4: "Quand tu t'abonnes après avoir été invité, l'ami qui t'a invité reçoit {n} jours de Premium offerts. Toi, tu profites de tout immédiatement.",
    sp_price_checkout: "Prix affiché à l'étape de paiement", sp_per_month: "/ mois", sp_per_months: "/ {n} mois", sp_per_year: "/ an", sp_per_years: "/ {n} ans", sp_per_week: "/ semaine", sp_per_weeks: "/ {n} semaines", sp_per_day: "/ jour", sp_per_days: "/ {n} jours", sp_trial: "{n} jours d'essai gratuit",
    plan_title: "Mon abonnement", plan_free: "Compte gratuit.", sp_r_3offers: "3 offres : Mensuel, Annuel ou Ultra", sp_r_2offers: "2 offres : avec ou sans engagement", sp_pl_commit: "Avec engagement", sp_pl_commit_d: "Premium, engagement 12 mois : le moins cher.", sp_pl_monthly_pay: "Payé chaque mois", sp_q5c: "Comment marche l'offre avec engagement ?", sp_a5c: "Tu paies chaque mois, moins cher que sans engagement, et tu t'engages pour 12 mois : la résiliation n'est pas possible pendant cette première année. Au bout des 12 mois, l'abonnement continue au même prix et devient résiliable à tout moment.", sp_a1c: "Avec l'offre sans engagement, oui : tu résilies quand tu veux avec « Gérer mon abonnement » et tu gardes ton accès jusqu'à la fin du mois payé. Avec l'offre avec engagement, tu t'engages pour 12 mois ; ensuite elle devient résiliable à tout moment.", sp_a7c: "Depuis l'offre sans engagement, tu peux résilier puis choisir l'offre avec engagement. Pendant les 12 mois d'engagement, l'offre ne peut pas être changée.", sp_commit_until: "Engagement jusqu'au {date}", sp_see_offers: "Voir les offres", sp_offers: "Choisis ton offre", sp_compare3: "Gratuit, Premium ou Ultra : ce qui est inclus", sp_manage: "Gérer mon abonnement", sp_from: "dès", sp_soon: "Bientôt disponible", sp_eq: "soit {amount} / mois", sp_save: "−{n} %", sp_best: "Le plus avantageux", sp_choose: "Choisir {name}", sp_current: "Ton offre actuelle", sp_switch: "Changer d'offre", sp_your_plan: "Ton offre : {name} — merci !",
    sp_pl_monthly: "Sans engagement", sp_pl_monthly_d: "Premium, résiliable à tout moment.", sp_pl_yearly: "Annuel", sp_pl_yearly_d: "Premium, engagement 1 an : le moins cher.", sp_pl_ultra: "Ultra", sp_pl_ultra_d: "Tout Premium, plus les outils IA avancés.",
    sp_pl_all: "Tout Premium : niveaux C1-C2, leçons et révisions illimitées, examens, certificats…", sp_pl_nocommit: "Sans engagement", sp_pl_cancel: "Annulable à tout moment", sp_pl_12: "Engagement 12 mois", sp_pl_once: "Payé en une fois par an", sp_pl_allprem: "Tout Premium inclus", sp_pl_corrector: "Correcteur de textes par l'IA", sp_pl_ai: "Jusqu'à {n} messages IA par jour", sp_pl_badge: "Badge Ultra",
    sp_g_ultra: "Ultra", sp_f_corrector: "Correcteur de textes IA", sp_d_corrector: "Pap’pote corrige tes mails, lettres et rédactions et explique chaque erreur", sp_f_ultrabadge: "Badge Ultra", sp_d_ultrabadge: "Affiché sur ton profil",
    sp_q5: "Comment marche l'offre Annuelle ?", sp_a5: "Tu paies 12 mois en une fois, moins cher que 12 mois au mensuel. C'est un engagement d'un an : pas de remboursement en cours d'année, mais tu peux désactiver le renouvellement à tout moment et l'offre s'arrête au bout des 12 mois.", sp_q6: "Qu'apporte Ultra en plus ?", sp_a6: "Tout Premium, plus le correcteur de textes par l'IA (Pap’pote corrige tes mails, lettres et rédactions et explique chaque erreur), beaucoup plus de messages avec l'IA chaque jour et le badge Ultra.", sp_q7: "Puis-je changer d'offre ?", sp_a7: "Oui, à tout moment depuis « Gérer mon abonnement » : le changement est calculé au prorata par Stripe.", sp_a1b: "Mensuel et Ultra sont sans engagement : tu annules quand tu veux avec « Gérer mon abonnement », et tu gardes ton accès jusqu'à la fin du mois déjà payé.",
    sp_already: "Tu es déjà Premium — merci !", sp_until: "Premium offert jusqu'au {date}",
    sp_g_learn: "📚 Apprendre", sp_g_review: "🧠 Réviser et progresser", sp_g_speak: "🎙️ Écouter et parler", sp_g_more: "🏆 Motivation",
    sp_v_3day: "3 leçons / jour", sp_v_unlimited: "Illimité", sp_v_20day: "20 / jour", sp_v_srs: "Illimité + prévisions", sp_v_20words: "20 mots", sp_v_msgs: "{n} messages / jour", sp_v_some: "Selon la langue",
    sp_f_langs: "39 langues, du A1 au B2", sp_d_langs: "Vocabulaire, phrases, grammaire, conjugaison, lecture, écoute et quiz.",
    sp_f_daily: "Leçon du jour et test de niveau", sp_d_daily: "Un parcours guidé de 5 minutes par jour, au bon niveau.",
    "sp_f_levels-c": "Niveaux C1 et C2", "sp_d_levels-c": "Mots, phrases, leçons et examens des niveaux avancés.",
    sp_f_lessons: "Leçons", sp_d_lessons: "8 nouveaux mots puis un quiz, autant que tu veux.",
    "sp_f_lecons-avancees": "Leçons avancées (B1 et plus)", "sp_d_lecons-avancees": "Les leçons des niveaux intermédiaires et avancés.",
    "sp_f_exercices-avances": "Exercices avancés", "sp_d_exercices-avances": "Écriture, dictée, texte à trous, remise en ordre, conjugaison.",
    sp_f_exam: "Examens blancs", sp_d_exam: "Un examen par niveau pour valider tes acquis.",
    sp_f_srs: "Révision espacée", sp_d_srs: "Les mots reviennent au bon moment pour ne pas les oublier (algorithme SM-2 en Premium).",
    sp_f_feedback: "Explications des erreurs", sp_d_feedback: "Pourquoi c'était faux, avec un exemple et l'analyse de ta réponse.",
    sp_f_stats: "Statistiques avancées", sp_d_stats: "Ta réussite par thème, par niveau et dans le temps.",
    sp_f_progress: "Progression mot par mot", sp_d_progress: "Le détail de chaque mot : vu, su, à revoir.",
    sp_f_custom: "Mots personnels", sp_d_custom: "Ajoute tes propres mots à réviser.",
    sp_f_export: "Export de la progression", sp_d_export: "Télécharge tes résultats (CSV).",
    sp_f_audio: "Audio de chaque mot", sp_d_audio: "Voix naturelles pré-enregistrées et vitesse réglable.",
    sp_f_compare: "Enregistrer et comparer", sp_d_compare: "Écoute ta voix à côté du modèle, sur tous les navigateurs.",
    sp_f_pron: "Score de prononciation", sp_d_pron: "La reconnaissance vocale note ta prononciation.",
    sp_f_ai: "Conversation avec Pap’pote (IA)", sp_d_ai: "Discute dans la langue, Pap’pote corrige tes phrases.",
    sp_f_friends: "Amis et défis de la semaine", sp_d_friends: "Classement entre amis et parrainage.",
    sp_f_badges: "Badges et succès", sp_d_badges: "Des récompenses pour chaque étape franchie.",
    sp_f_cert: "Certificats de niveau", sp_d_cert: "Un certificat imprimable quand tu valides un niveau.",
    sp_f_offline: "Mode hors-ligne", sp_d_offline: "Continue à apprendre sans connexion.",
    sp_f_noads: "Sans publicité", sp_d_noads: "Ni publicité ni revente de données, gratuit ou Premium.",
    glass_title: "Apparence · Liquid Glass", glass_lead: "Règle la transparence du verre, de « ultra-clair » à « teinté », comme dans les Réglages d'iOS 27. Le réglage s'applique à tout Pap’pote sur cet appareil.", glass_label: "Transparence du verre", glass_clear: "Ultra-clair", glass_tinted: "Teinté", glass_regular: "Équilibré", glass_preview: "Aperçu du verre", glass_card: "Carte", glass_system: "« Réduire la transparence » ou « Augmenter le contraste » est activé sur ton appareil : le verre reste opaque pour la lisibilité.",
    mod_amis: "Amis & défis", desc_amis: "Classement de la semaine et parrainage", friends_sub: "Ajoute tes amis avec leur code et comparez vos XP de la semaine.", week_challenge: "Défi de la semaine", week_challenge_d: "XP gagnés depuis lundi, toutes langues confondues. Le classement repart à zéro chaque lundi.", no_friends: "Pas encore d'amis ici : partage ton code ou ton lien d'invitation !", my_code: "Mon code ami", invite_friend: "Inviter un ami", copy_code: "Copier le code", copied: "Code copié", link_copied: "Lien d'invitation copié", invite_text: "J'apprends le {lang} avec Pap’pote 🐱 Rejoins-moi et défions-nous chaque semaine !", referral_d: "Quand un ami invité avec ton lien prend Premium, tu gagnes {n} jours de Premium offerts.", referral_stats: "{n} ami(s) invité(s) · {r} récompense(s) obtenue(s)", add_friend: "Ajouter un ami", friend_code_label: "Code ami (8 caractères)", add: "Ajouter", friend_added: "Ami ajouté !", friend_remove: "Retirer", friend_remove_confirm: "Retirer cet ami de ta liste ?", you: "toi",
    outfit_title: "Tenue de Pap’pote", outfit_d: "Gagne des XP dans cette langue pour débloquer des accessoires.", outfit_locked: "Débloqué à {n} XP", outfit_saved: "Nouvelle tenue !", outfit_none: "Aucune", outfit_scarf: "Écharpe", outfit_bow: "Nœud", outfit_flower: "Fleur", outfit_cap: "Casquette", outfit_grad: "Toque de diplômé", outfit_crown: "Couronne",
    corr_title: "Correcteur de textes", corr_d: "Écris un texte (mail, lettre, rédaction…) dans la langue : Pap’pote le corrige et t'explique chaque erreur.", corr_go: "Passer à Ultra", corr_ph: "Écris ton texte ici…", corr_btn: "Corriger mon texte", corr_wait: "Pap’pote corrige…", corr_score: "Ton texte était juste à {n} %", corr_fixed: "Texte corrigé", corr_notes: "Les corrections", corr_perfect: "Aucune faute, bravo !", 
    mod_conversation: "Conversation IA", desc_conversation: "Discute avec Pap’pote, qui corrige tes phrases", chat_sub: "Pap’pote te répond dans la langue, à ton niveau, et corrige gentiment tes erreurs.", chat_scenario: "Situation", chat_level: "Niveau", chat_new: "Nouvelle conversation", chat_start: "Commencer", chat_intro: "Choisis une situation et ton niveau, puis lance la conversation : Pap’pote commence !", chat_ph: "Écris ta réponse…", chat_send: "Envoyer", chat_translate: "Traduire", chat_typing: "Pap’pote écrit…", chat_left: "{n} messages restants aujourd'hui (sur {max})", chat_quota: "Tu as utilisé tous tes messages du jour. Reviens demain, ou passe à Premium pour en avoir beaucoup plus.", chat_disabled: "La conversation IA n'est pas encore activée sur ce serveur.", chat_error: "Pap’pote n'a pas pu répondre. Réessaie.",
    sc_free: "Discussion libre", sc_cafe: "Au café", sc_travel: "Demander son chemin", sc_intro: "Se présenter", sc_shopping: "Faire les courses", sc_doctor: "Chez le médecin", sc_job: "Entretien d'embauche", sc_debate: "Petit débat",
    daily_title: "Leçon du jour", daily_d: "{r} révisions, {n} nouveaux mots puis un quiz — environ 5 minutes.", daily_d_new: "{n} nouveaux mots puis un quiz — environ 5 minutes.", daily_start: "Commencer", daily_done: "Leçon du jour terminée — reviens demain !", daily_again: "Refaire une leçon", daily_step_review: "Étape 1 · Révisions", daily_step_new: "Étape 2 · Nouveaux mots", daily_level: "Niveau conseillé : {level}",
    place_title: "Trouve ton niveau", place_d: "Un vrai test (10 à 15 minutes) : vocabulaire, écoute, grammaire, lecture et écriture. Il s'adapte à tes réponses, du A1 au C2.", place_q2: "Partie {part} · question {i}/{n}", place_meaning_q: "Que signifie ce mot ?", place_recall_q: "Comment dit-on… ?", place_listen_q: "Écoute et choisis le sens", place_ctx_q: "Complète la phrase", place_phrase_q: "Que veut dire cette phrase ?", place_conj_q: "Conjugue « {verb} » ({tense})", place_read_q: "Lis le texte puis réponds", place_type_q: "Écris-le en {lang}", place_type_ph: "Ta réponse…", place_check: "Valider", place_note: "Les bonnes réponses ne sont pas affichées pendant le test : réponds « Je ne sais pas » plutôt que de deviner.", place_acquired: "Niveau acquis : {level}", place_none: "Niveau acquis : débutant", place_work: "Ta leçon du jour travaillera le niveau {level}. Tu peux refaire le test quand tu veux dans ton profil.", place_partial: "Le niveau {level} est en cours d'acquisition ({pct} %).", place_by_level: "Résultats par niveau", place_by_skill: "Résultats par compétence", place_sk_vocab: "Vocabulaire", place_sk_listen: "Compréhension orale", place_sk_grammar: "Grammaire et conjugaison", place_sk_reading: "Compréhension écrite", place_sk_writing: "Orthographe", place_start: "Faire le test", place_skip: "Je débute", place_q: "Niveau {level} · question {i}/{n}", place_result: "Ton niveau conseillé : {level}", place_result_d: "Ta leçon du jour partira de là. Tu peux refaire le test quand tu veux dans ton profil.", place_redo: "Refaire le test de niveau", dont_know: "Je ne sais pas", place_beyond: "Tu maîtrises tout le contenu gratuit : les niveaux C sont dans Premium.",
    profile_sub: "Ta langue de base, l'audio et tes réglages pour cette langue.", base_lang: "Langue de base", change: "Modifier", audio: "Audio", speech_rate: "Vitesse", voice: "Voix", voice_source: "Source de la voix", voice_papote: "Voix Pap’pote (recommandée)", voice_device: "Voix de l'appareil", auto: "Automatique", settings: "Réglages", show_rom: "Afficher la prononciation / romanisation", autoplay: "Lecture audio automatique", daily_goal: "Objectif quotidien", danger: "Zone sensible", reset_progress: "Réinitialiser ma progression dans cette langue", reset_confirm: "Effacer toute ta progression dans cette langue ?",
    offline_on: "Mode hors-ligne actif pour cette langue.", offline_preparing: "Préparation du mode hors-ligne…", offline_unsupported: "Le mode hors-ligne n'est pas disponible sur ce navigateur.",
    goal_reached: "Objectif du jour atteint ({n} XP) !", theme_toggle: "Mode clair / sombre",
    // app shell / hub / shell pages
 back_home: "Retour à l'accueil", ideas_title: "Boîte à idées", ideas_lead: "Une idée de langue, une fonctionnalité qui te manque, un bug repéré ? Écris-le ici : chaque message est lu.", ideas_cat: "Catégorie", cat_fonctionnalite: "Fonctionnalité", cat_contenu: "Contenu (mots, leçons, exercices)", cat_langue: "Nouvelle langue", cat_design: "Design", cat_bug: "Bug", cat_autre: "Autre", ideas_label: "Ton idée", ideas_ph: "Ex : ajouter des dialogues audio en coréen…", send: "Envoyer", sending: "Envoi…", ideas_short: "Décris un peu plus ton idée.", ideas_thanks: "Merci ! Ton idée a bien été enregistrée.", send_error: "Impossible d'envoyer pour le moment.", net_error: "Erreur réseau.", ideas_note: "Chaque idée est lue par l'équipe et reçoit un statut (vue, en cours, acceptée ou refusée).",
    reminder_title: "Rappel quotidien", reminder_lead: "Un petit email à l'heure choisie, seulement les jours où tu n'as pas encore pratiqué. Désinscription en un clic.", reminder_enable: "M'envoyer un rappel par email", reminder_hour: "Heure du rappel", reminder_unverified: "Confirme d'abord ton adresse email : les rappels ne partent qu'aux adresses vérifiées.",
    profile_title: "Mon profil", profile_lead: "Ton nom et ta langue de base — celle que tu parles déjà. Toute l'application s'y adapte : interface, traductions, explications et parcours.", name_label: "Prénom / nom affiché", name_ph: "Ton prénom", save: "Enregistrer", saving: "Enregistrement…", saved: "Profil enregistré ✓", save_error: "Impossible d'enregistrer pour le moment.", profile_note: "Exemple : langue de base français + langue apprise japonais = interface, traductions des mots et des phrases, et explications en français, contenu en japonais. Les explications de grammaire et de culture sont rédigées en français et en anglais : pour les autres langues de base, la version anglaise est utilisée.",
    app_name: "Pap’pote", hub_choose: "Choisis une langue pour commencer", hub_hello: "Bonjour {name} 👋", hub_base: "langue de base : {lang}", admin: "Admin", profile: "Profil", ideas: "Idées", reorder: "Réorganiser", reorder_done: "Terminé", logout: "Se déconnecter", premium_cta: "Toutes les langues sont gratuites — Premium ajoute les niveaux C1/C2, les leçons illimitées, la révision avancée, les certificats et bien plus", all_languages: "Toutes les langues", soon: "Bientôt",
  };

  D.en = {
    kids_title: "Kids mode", kids_lead: "A simple, colourful version for children: picture stories, picture games, a picture dictionary and stickers to collect. Going back to adult mode asks a small sum.", kids_go: "Switch to kids mode", mode_label: "Mode", mode_adult: "Adult", mode_kids: "Kids", mode_to_kids: "Kids mode", mode_to_adult: "Adult mode", gate_title: "A question for grown-ups", gate_lead: "To go back to adult mode, answer this sum:", gate_ok: "OK", gate_cancel: "Cancel",
    invoices_title: "My invoices", invoices_lead: "Your Premium invoices, as PDF.",
    data_title: "My data", data_lead: "You can download everything the app stores about you, log out of all your devices or permanently delete your account.", data_export: "Download my data", logout_all: "Log out of all devices", delete_account: "Delete my account", delete_lead: "Deleting erases your account, progress and ideas. Invoices are kept for accounting, no longer linked to your account. Confirm with your password.", delete_pw_ph: "Your password", delete_confirm: "Permanently delete your account? This cannot be undone.", wrong_password: "Wrong password.", email_unverified: "Email address not confirmed: click the link we emailed you.",
    sub_btn: "Subscribe", sub_no_commit: "No commitment, cancel anytime", sub_no_ads: "No ads, ever", sub_canceled: "Payment canceled.", sub_success: "Payment received, thank you! Your Premium access is active.", sub_redirect: "Redirecting…", sub_unavailable: "Payment isn't available yet.",
    load_error: "This module could not be loaded.", loading: "Loading…",
    learn_lang: "Learning: {lang}", modules: "Modules", go_premium: "Premium", speaking: "Playing audio…", listen: "Listen",
    tts_unsupported: "Audio is not available in this browser.", tts_no_voice: "No “{lang}” voice is installed on this device: audio uses the default voice.", tts_approx: "Approximate voice: no native voice exists for this language on this device.",
    gloss_fallback: "No translation in your base language yet: another language is shown instead.",
    premium_only: "Premium only", premium_unlock: "upgrade to Premium to unlock it.", premium_title: "Premium", premium_sub: "Everything you need to go all the way, in all 39 languages.", premium_tools: "Premium tools",
    "feat_levels-c": "C1 and C2 levels (words, lessons, exams)", "feat_lessons-unlimited": "Unlimited lessons", "feat_srs-advanced": "Advanced spaced repetition (SM-2, forecast, no limit)", "feat_pronunciation-ai": "Pronunciation with speech recognition and scoring", "feat_stats-advanced": "Advanced statistics", "feat_progress-detailed": "Word-by-word progress", "feat_certificates": "Level certificates", "feat_badges": "Badges and achievements", "feat_offline": "Offline mode", "feat_custom-words": "Unlimited personal words", "feat_exam": "Practice exams per level", "feat_export": "Progress export (CSV)", "feat_exercices-avances": "Advanced exercises (writing, dictation, gap-fill, word order, conjugation)", "feat_lecons-avancees": "Advanced lessons (B1 and above)", "feat_feedback-avance": "Advanced feedback (explanations, error analysis)",
    mod_hub: "Home", mod_vocabulaire: "Vocabulary", mod_phrases: "Useful phrases", mod_grammaire: "Grammar", mod_conjugaison: "Conjugation", mod_alphabet: "Alphabet", mod_lecture: "Reading", mod_ecoute: "Listening", mod_exercices: "Exercises", mod_revision: "Review", mod_prononciation: "Pronunciation", mod_culture: "Culture", mod_examen: "Exams", mod_stats: "Statistics", mod_badges: "Badges", mod_certificat: "Certificates", mod_dictionnaire: "Dictionary", mod_profil: "Profile", mod_levels: "Level",
    desc_vocabulaire: "Every word, by topic and level", desc_phrases: "Everyday phrases, with audio", desc_grammaire: "The essential rules, explained", desc_conjugaison: "Tables and practice", desc_alphabet: "The script, letter by letter", desc_lecture: "Texts by level, with questions", desc_ecoute: "Listening, dictation, audio texts", desc_exercices: "Quizzes, writing, gap-fill, word order…", desc_revision: "Spaced repetition", desc_prononciation: "Listen and repeat", desc_culture: "Customs, history, landmarks", desc_examen: "Test your level A1 → C2", desc_stats: "Your progress in numbers", desc_badges: "Your achievements", desc_certificat: "Printable certificates", desc_dictionnaire: "Search and add words", desc_profil: "Settings and audio",
    level: "Level", level_A1: "Beginner", level_A2: "Elementary", level_B1: "Intermediate", level_B2: "Upper intermediate", level_C1: "Advanced", level_C2: "Proficiency",
    all_levels: "All", all_themes: "All topics", theme: "Topic", sort: "Sort", filter: "Filter", search: "Search…",
    sort_theme: "By topic", sort_level: "By level", sort_alpha: "A → Z", sort_learn: "To learn first",
    only_all: "All words", only_new: "Never seen", only_known: "Already known",
    hub_intro: "Your {lang} path: vocabulary, grammar, reading, listening and exercises, from A1 to C2.",
    xp: "XP", streak_days: "day streak", words_known: "words known", accuracy: "accuracy", answers: "answers",
    reviews_due: "{n} words to review today", review_now: "Review", word_of_day: "Word of the day", cefr_levels: "CEFR levels", explore: "Explore",
    n_words: "{n} words", n_known: "{n} known", n_shown: "{n} shown of {total}", n_texts: "{n} texts", n_questions: "{n} questions",
    vocab_sub: "{n} words, each with its CEFR level. Tap a word to see an example.", show_more: "Show more", no_results: "No results.",
    locked_levels: "{n} words at level {levels} are Premium only.", plural: "Plural", mine: "mine", known: "Known", in_review: "In review", add_review: "Add to review", added_review: "Added to review", added_n: "{n} words added to review", my_words: "My words",
    phrases_sub: "The phrases you need every day, each with audio.", grammar_sub: "The core rules of {lang}, with audio examples.", pronunciation_rules: "Pronunciation",
    conj_sub: "Pick a verb to see its forms, with audio.", irregular: "irregular", practice: "Practice",
    alphabet_sub: "Tap a letter to hear it and see an example.", sound: "sound",
    reading_sub: "Texts sorted by level: listen, show the translation, answer the questions.", listen_text: "Listen to the text", show_text: "Show text", show_translation: "Translation",
    listening_sub: "Train your ear: listen first, read afterwards.", listen_texts: "Texts to listen to",
    exercises_sub: "Pick a level, a topic and an exercise type.",
    mode_mcq: "Multiple choice", mode_mcq_d: "Choose the right translation", mode_reverse: "Reverse translation", mode_reverse_d: "Find the word from its meaning", mode_listen: "Listening", mode_listen_d: "Listen and choose the meaning", mode_write: "Writing", mode_write_d: "Type the word (virtual keyboard)", mode_dictation: "Dictation", mode_dictation_d: "Write what you hear", mode_cloze: "Gap-fill", mode_cloze_d: "Complete the sentence", mode_order: "Word order", mode_order_d: "Put the sentence back in order", mode_conj: "Conjugation", mode_conj_d: "Choose the right form", mode_mix: "Mix", mode_mix_d: "A bit of everything",
    quit: "Quit", check: "Check", continue: "Continue", correct: "Correct!", wrong: "Not quite…", answer_was: "Answer", example: "Example", similarity: "Your answer is {n}% close.", feedback_locked: "Detailed explanations come with advanced feedback (Premium).",
    quiz_done: "Round complete", score_line: "{ok}/{total} correct ({pct}%) · +{xp} XP", again: "Again", back: "Back", review_errors: "Your mistakes", you_said: "your answer", reset: "Clear",
    srs_adv_sub: "SM-2 algorithm: each word comes back just before you'd forget it.", srs_free_sub: "Box-based spaced repetition, {n} reviews a day.", due_now: "due", in_srs: "in review", left_today: "left today",
    srs_cap_reached: "Daily limit reached. Premium: unlimited reviews.", nothing_due: "Nothing to review right now.", learn_new: "Add new words", forecast: "7-day forecast", today: "Today",
    review_done: "Review complete!", show_answer: "Show answer", grade_again: "Again", grade_hard: "Hard", grade_good: "Good", grade_easy: "Easy",
    pron_sub_ai: "Listen, then record yourself: your pronunciation is compared with the model and scored.", pron_sub_free: "Listen and repeat out loud.", sr_unsupported: "Speech recognition is not available in this browser (try Chrome or Safari).", record: "Speak", listening: "Listening…", heard: "heard", pron_great: "Excellent!", pron_ok: "Not bad, one more try?", pron_retry: "Try again, articulating clearly.", sr_error: "Microphone unavailable",
    culture_sub: "Customs, history and landmarks to understand the {lang}-speaking world.",
    lesson: "Lesson", lesson_d: "8 new words, then a 10-question quiz.", start_lesson: "Start the lesson", lessons_left: "{n} free lessons left today", lessons_cap: "You've done your 3 free lessons today.", lesson_done: "Lesson complete!", new_word: "New word", words_of_level: "{level} words",
    exam_d: "20 questions. 80% to pass and earn the certificate.", exam_best: "Best score: {n}%", take_exam: "Take the exam", exam_sub: "One exam per level: 20 questions, 80% to pass.", not_taken: "Not taken yet", exam_passed: "Level {level} passed!", exam_failed: "Not yet: you need 80%.", not_enough: "Not enough words at this level.",
    stats_sub: "Your progress in this language.", activity_30: "Activity (30 days)", by_level: "By level", by_theme: "By topic (weakest first)", hardest_words: "Hardest words",
    badges_sub: "{n} of {total} badges.", earned_on: "earned on {d}", badge_new: "New badge: {name}",
    badge_first: "First step", badge_first_d: "Answer a first question", badge_lesson1: "First lesson", badge_lesson1_d: "Finish a lesson", badge_lesson10: "Dedicated", badge_lesson10_d: "Finish 10 lessons", badge_words50: "50 words", badge_words50_d: "Know 50 words", badge_words250: "250 words", badge_words250_d: "Know 250 words", badge_words1000: "1,000 words", badge_words1000_d: "Know 1,000 words", badge_streak3: "On a roll", badge_streak3_d: "3 days in a row", badge_streak7: "One week", badge_streak7_d: "7 days in a row", badge_streak30: "One month", badge_streak30_d: "30 days in a row", badge_xp1000: "1,000 XP", badge_xp1000_d: "Earn 1,000 XP", badge_perfect: "Flawless", badge_perfect_d: "A perfect round", badge_reviewer: "Elephant memory", badge_reviewer_d: "100 words in review", badge_examA: "Level A", badge_examA_d: "Pass an A1 or A2 exam", badge_examB: "Level B", badge_examB_d: "Pass a B1 or B2 exam", badge_examC: "Level C", badge_examC_d: "Pass a C1 or C2 exam", badge_speaker: "Speaker", badge_speaker_d: "10 successful pronunciations",
    no_cert: "No certificate yet", no_cert_d: "Pass a level exam (80%) to get your certificate.", print: "Print", cert_title: "Certificate of achievement", cert_attests: "This certifies that", cert_body: "has passed CEFR level {level} ({label}) in {lang}, with a score of {score}%.", cert_date: "Issued on {d}", learner: "Learner",
    dict_sub: "Search for a word, a phrase or a rule — or add your own words.", word_in: "Word in {lang}", romanization: "Pronunciation / romanization", translation: "Translation", word_required: "The word and its translation are required.",
    sr_fallback: "This browser has no speech recognition: use “Record and compare” — you hear the model then your voice, with both waveforms side by side.", rec_unsupported: "Audio recording isn't available here: listen and repeat out loud.", rec_compare: "Record and compare", rec_stop: "Stop", rec_me: "My voice", rec_model: "Model", rec_self: "How was it?", rec_good: "Good", rec_again: "Needs work", mic_denied: "Microphone blocked or unavailable: allow it in your browser.",
    progress: "Progress", progress_text: "{kind} {i} of {n} ({pct}%)", progress_question: "Question", progress_step: "Step",
    legal_notice: "Legal notice", privacy_policy: "Privacy",
    sp_title: "All of Pap’pote, no limits", sp_lead: "All 39 languages stay free up to level B2. Premium unlocks the rest: C1-C2 levels, unlimited lessons and reviews, advanced exercises, exams, certificates…",
    sp_r1: "No commitment, cancel in one click", sp_r2: "Secure payment with Stripe", sp_r3: "No ads, ever",
    sp_compare: "Free or Premium: what's included", sp_feature: "Feature", sp_free: "Free", sp_yes: "included", sp_no: "not included", sp_faq: "Frequently asked questions",
    sp_q1: "Can I cancel anytime?", sp_a1: "Yes, no commitment: cancel from the link in your email or the Stripe portal, and keep Premium until the end of the period already paid.",
    sp_q2: "What happens if I stop Premium?", sp_a2: "You go back to the free plan without losing anything: your progress, words and badges stay in your account. Only Premium content gets locked again.",
    sp_q3: "Is the payment secure?", sp_a3: "Payment happens on Stripe's secure page: Pap’pote never sees or stores your card. An invoice is emailed to you.",
    sp_q4: "What if a friend invited me?", sp_a4: "When you subscribe after being invited, the friend who invited you gets {n} days of Premium for free. You enjoy everything right away.",
    sp_price_checkout: "Price shown at checkout", sp_per_month: "/ month", sp_per_months: "/ {n} months", sp_per_year: "/ year", sp_per_years: "/ {n} years", sp_per_week: "/ week", sp_per_weeks: "/ {n} weeks", sp_per_day: "/ day", sp_per_days: "/ {n} days", sp_trial: "{n}-day free trial",
    plan_title: "My subscription", plan_free: "Free account.", sp_r_3offers: "3 offers: Monthly, Yearly or Ultra", sp_r_2offers: "2 offers: with or without commitment", sp_pl_commit: "With commitment", sp_pl_commit_d: "Premium, 12-month commitment: the cheapest.", sp_pl_monthly_pay: "Paid every month", sp_q5c: "How does the commitment offer work?", sp_a5c: "You pay every month, less than without commitment, and commit for 12 months: you can't cancel during that first year. After 12 months the subscription continues at the same price and can be cancelled anytime.", sp_a1c: "With the no-commitment offer, yes: cancel anytime with “Manage my subscription” and keep access until the end of the paid month. With the commitment offer you commit for 12 months; after that you can cancel anytime.", sp_a7c: "From the no-commitment offer you can cancel and then pick the commitment offer. During the 12-month commitment the offer can't be changed.", sp_commit_until: "Committed until {date}", sp_see_offers: "See the offers", sp_offers: "Pick your offer", sp_compare3: "Free, Premium or Ultra: what's included", sp_manage: "Manage my subscription", sp_from: "from", sp_soon: "Coming soon", sp_eq: "that's {amount} / month", sp_save: "−{n}%", sp_best: "Best value", sp_choose: "Choose {name}", sp_current: "Your current offer", sp_switch: "Change offer", sp_your_plan: "Your offer: {name} — thank you!",
    sp_pl_monthly: "No commitment", sp_pl_monthly_d: "Premium, cancel anytime.", sp_pl_yearly: "Yearly", sp_pl_yearly_d: "Premium, 1-year commitment: the cheapest.", sp_pl_ultra: "Ultra", sp_pl_ultra_d: "All of Premium, plus advanced AI tools.",
    sp_pl_all: "All of Premium: C1-C2 levels, unlimited lessons and reviews, exams, certificates…", sp_pl_nocommit: "No commitment", sp_pl_cancel: "Cancel anytime", sp_pl_12: "12-month commitment", sp_pl_once: "Paid once a year", sp_pl_allprem: "All of Premium included", sp_pl_corrector: "AI text corrector", sp_pl_ai: "Up to {n} AI messages a day", sp_pl_badge: "Ultra badge",
    sp_g_ultra: "Ultra", sp_f_corrector: "AI text corrector", sp_d_corrector: "Pap’pote corrects your emails, letters and essays and explains every mistake", sp_f_ultrabadge: "Ultra badge", sp_d_ultrabadge: "Shown on your profile",
    sp_q5: "How does the Yearly offer work?", sp_a5: "You pay 12 months at once, cheaper than 12 monthly payments. It's a one-year commitment: no refund during the year, but you can turn off renewal anytime and the offer ends after 12 months.", sp_q6: "What does Ultra add?", sp_a6: "All of Premium, plus the AI text corrector (Pap’pote corrects your emails, letters and essays and explains every mistake), many more AI messages a day and the Ultra badge.", sp_q7: "Can I change offer?", sp_a7: "Yes, anytime from “Manage my subscription”: Stripe prorates the change.", sp_a1b: "Monthly and Ultra have no commitment: cancel anytime with “Manage my subscription” and keep access until the end of the month already paid.",
    sp_already: "You're already Premium — thank you!", sp_until: "Free Premium until {date}",
    sp_g_learn: "📚 Learn", sp_g_review: "🧠 Review and progress", sp_g_speak: "🎙️ Listen and speak", sp_g_more: "🏆 Motivation",
    sp_v_3day: "3 lessons / day", sp_v_unlimited: "Unlimited", sp_v_20day: "20 / day", sp_v_srs: "Unlimited + forecast", sp_v_20words: "20 words", sp_v_msgs: "{n} messages / day", sp_v_some: "Depends on the language",
    sp_f_langs: "39 languages, A1 to B2", sp_d_langs: "Vocabulary, phrases, grammar, conjugation, reading, listening and quizzes.",
    sp_f_daily: "Daily lesson and level test", sp_d_daily: "A guided 5-minute path every day, at the right level.",
    "sp_f_levels-c": "C1 and C2 levels", "sp_d_levels-c": "Words, phrases, lessons and exams of the advanced levels.",
    sp_f_lessons: "Lessons", sp_d_lessons: "8 new words then a quiz, as many as you like.",
    "sp_f_lecons-avancees": "Advanced lessons (B1 and up)", "sp_d_lecons-avancees": "Lessons of the intermediate and advanced levels.",
    "sp_f_exercices-avances": "Advanced exercises", "sp_d_exercices-avances": "Writing, dictation, gap-fill, word order, conjugation.",
    sp_f_exam: "Mock exams", sp_d_exam: "One exam per level to validate what you know.",
    sp_f_srs: "Spaced repetition", sp_d_srs: "Words come back at the right time so you don't forget them (SM-2 algorithm in Premium).",
    sp_f_feedback: "Mistake explanations", sp_d_feedback: "Why it was wrong, with an example and an analysis of your answer.",
    sp_f_stats: "Advanced statistics", sp_d_stats: "Your success by topic, by level and over time.",
    sp_f_progress: "Word-by-word progress", sp_d_progress: "Every word in detail: seen, known, to review.",
    sp_f_custom: "Personal words", sp_d_custom: "Add your own words to review.",
    sp_f_export: "Progress export", sp_d_export: "Download your results (CSV).",
    sp_f_audio: "Audio for every word", sp_d_audio: "Natural pre-recorded voices, adjustable speed.",
    sp_f_compare: "Record and compare", sp_d_compare: "Hear your voice next to the model, in every browser.",
    sp_f_pron: "Pronunciation score", sp_d_pron: "Speech recognition scores your pronunciation.",
    sp_f_ai: "Chat with Pap’pote (AI)", sp_d_ai: "Talk in the language, Pap’pote corrects your sentences.",
    sp_f_friends: "Friends and weekly challenges", sp_d_friends: "Leaderboard with friends and referrals.",
    sp_f_badges: "Badges and achievements", sp_d_badges: "Rewards for every milestone.",
    sp_f_cert: "Level certificates", sp_d_cert: "A printable certificate when you complete a level.",
    sp_f_offline: "Offline mode", sp_d_offline: "Keep learning without a connection.",
    sp_f_noads: "No ads", sp_d_noads: "No ads and no data selling, free or Premium.",
    glass_title: "Appearance · Liquid Glass", glass_lead: "Set how transparent the glass is, from “ultra clear” to “tinted”, like in iOS 27 Settings. It applies to all of Pap’pote on this device.", glass_label: "Glass transparency", glass_clear: "Ultra clear", glass_tinted: "Tinted", glass_regular: "Balanced", glass_preview: "Glass preview", glass_card: "Card", glass_system: "“Reduce transparency” or “Increase contrast” is on for your device: the glass stays opaque for legibility.",
    mod_amis: "Friends & challenges", desc_amis: "This week's leaderboard and referrals", friends_sub: "Add your friends with their code and compare this week's XP.", week_challenge: "Weekly challenge", week_challenge_d: "XP earned since Monday, all languages together. The leaderboard resets every Monday.", no_friends: "No friends here yet: share your code or your invitation link!", my_code: "My friend code", invite_friend: "Invite a friend", copy_code: "Copy code", copied: "Code copied", link_copied: "Invitation link copied", invite_text: "I'm learning {lang} with Pap’pote 🐱 Join me and let's challenge each other every week!", referral_d: "When a friend you invited goes Premium, you get {n} days of Premium for free.", referral_stats: "{n} friend(s) invited · {r} reward(s) earned", add_friend: "Add a friend", friend_code_label: "Friend code (8 characters)", add: "Add", friend_added: "Friend added!", friend_remove: "Remove", friend_remove_confirm: "Remove this friend from your list?", you: "you",
    outfit_title: "Pap’pote's outfit", outfit_d: "Earn XP in this language to unlock accessories.", outfit_locked: "Unlocked at {n} XP", outfit_saved: "New outfit!", outfit_none: "None", outfit_scarf: "Scarf", outfit_bow: "Bow", outfit_flower: "Flower", outfit_cap: "Cap", outfit_grad: "Graduation cap", outfit_crown: "Crown",
    corr_title: "Text corrector", corr_d: "Write a text (email, letter, essay…) in the language: Pap’pote corrects it and explains every mistake.", corr_go: "Go Ultra", corr_ph: "Write your text here…", corr_btn: "Correct my text", corr_wait: "Pap’pote is correcting…", corr_score: "Your text was {n}% correct", corr_fixed: "Corrected text", corr_notes: "Corrections", corr_perfect: "No mistakes, well done!", 
    mod_conversation: "AI conversation", desc_conversation: "Chat with Pap’pote, who corrects your sentences", chat_sub: "Pap’pote answers in the language, at your level, and kindly corrects your mistakes.", chat_scenario: "Situation", chat_level: "Level", chat_new: "New conversation", chat_start: "Start", chat_intro: "Pick a situation and your level, then start: Pap’pote speaks first!", chat_ph: "Type your answer…", chat_send: "Send", chat_translate: "Translate", chat_typing: "Pap’pote is typing…", chat_left: "{n} messages left today (out of {max})", chat_quota: "You've used all your messages for today. Come back tomorrow, or go Premium for many more.", chat_disabled: "The AI conversation isn't enabled on this server yet.", chat_error: "Pap’pote couldn't answer. Try again.",
    sc_free: "Free chat", sc_cafe: "At the café", sc_travel: "Asking for directions", sc_intro: "Introducing yourself", sc_shopping: "Shopping", sc_doctor: "At the doctor's", sc_job: "Job interview", sc_debate: "Friendly debate",
    daily_title: "Today's lesson", daily_d: "{r} reviews, {n} new words then a quiz — about 5 minutes.", daily_d_new: "{n} new words then a quiz — about 5 minutes.", daily_start: "Start", daily_done: "Today's lesson done — see you tomorrow!", daily_again: "Do another lesson", daily_step_review: "Step 1 · Reviews", daily_step_new: "Step 2 · New words", daily_level: "Suggested level: {level}",
    place_title: "Find your level", place_d: "A real test (10-15 minutes): vocabulary, listening, grammar, reading and writing. It adapts to your answers, from A1 to C2.", place_q2: "Part {part} · question {i}/{n}", place_meaning_q: "What does this word mean?", place_recall_q: "How do you say…?", place_listen_q: "Listen and pick the meaning", place_ctx_q: "Complete the sentence", place_phrase_q: "What does this sentence mean?", place_conj_q: "Conjugate “{verb}” ({tense})", place_read_q: "Read the text, then answer", place_type_q: "Write it in {lang}", place_type_ph: "Your answer…", place_check: "Check", place_note: "Answers are not shown during the test: pick “I don't know” rather than guessing.", place_acquired: "Level reached: {level}", place_none: "Level reached: beginner", place_work: "Your daily lesson will work on {level}. You can retake the test anytime from your profile.", place_partial: "{level} is in progress ({pct}%).", place_by_level: "Score per level", place_by_skill: "Score per skill", place_sk_vocab: "Vocabulary", place_sk_listen: "Listening", place_sk_grammar: "Grammar & conjugation", place_sk_reading: "Reading", place_sk_writing: "Spelling", place_start: "Take the test", place_skip: "I'm a beginner", place_q: "Level {level} · question {i}/{n}", place_result: "Your suggested level: {level}", place_result_d: "Your daily lesson will start from there. You can retake the test anytime from your profile.", place_redo: "Retake the level test", dont_know: "I don't know", place_beyond: "You've mastered all the free content: C levels are part of Premium.",
    profile_sub: "Your base language, audio and settings for this language.", base_lang: "Base language", change: "Change", audio: "Audio", speech_rate: "Speed", voice: "Voice", voice_source: "Voice source", voice_papote: "Pap’pote voice (recommended)", voice_device: "Device voice", auto: "Automatic", settings: "Settings", show_rom: "Show pronunciation / romanization", autoplay: "Play audio automatically", daily_goal: "Daily goal", danger: "Danger zone", reset_progress: "Reset my progress in this language", reset_confirm: "Erase all your progress in this language?",
    offline_on: "Offline mode is on for this language.", offline_preparing: "Preparing offline mode…", offline_unsupported: "Offline mode is not available in this browser.",
    goal_reached: "Daily goal reached ({n} XP)!", theme_toggle: "Light / dark mode",
 back_home: "Back to home", ideas_title: "Idea box", ideas_lead: "A language idea, a missing feature, a bug? Write it here: every message is read.", ideas_cat: "Category", cat_fonctionnalite: "Feature", cat_contenu: "Content (words, lessons, exercises)", cat_langue: "New language", cat_design: "Design", cat_bug: "Bug", cat_autre: "Other", ideas_label: "Your idea", ideas_ph: "E.g. add audio dialogues in Korean…", send: "Send", sending: "Sending…", ideas_short: "Describe your idea a bit more.", ideas_thanks: "Thanks! Your idea has been saved.", send_error: "Could not send right now.", net_error: "Network error.", ideas_note: "Every idea is read by the team and gets a status (seen, in progress, accepted or declined).",
    reminder_title: "Daily reminder", reminder_lead: "A short email at the time you choose, only on days you haven't practised yet. One-click unsubscribe.", reminder_enable: "Send me a reminder by email", reminder_hour: "Reminder time", reminder_unverified: "Confirm your email address first: reminders only go to verified addresses.",
    profile_title: "My profile", profile_lead: "Your name and your base language — the one you already speak. The whole app adapts to it: interface, translations, explanations and learning path.", name_label: "Display name", name_ph: "Your first name", save: "Save", saving: "Saving…", saved: "Profile saved ✓", save_error: "Could not save right now.", profile_note: "Example: base language English + learning Japanese = interface, word and phrase translations and explanations in English, content in Japanese. Grammar and culture explanations are written in French and English: other base languages get the English version.",
    app_name: "Pap’pote", hub_choose: "Pick a language to get started", hub_hello: "Hi {name} 👋", hub_base: "base language: {lang}", admin: "Admin", profile: "Profile", ideas: "Ideas", reorder: "Reorder", reorder_done: "Done", logout: "Log out", premium_cta: "Every language is free — Premium adds C1/C2 levels, unlimited lessons, advanced review, certificates and much more", all_languages: "All languages", soon: "Soon",
  };

  function resolve(code) { return AVAILABLE.indexOf(code) >= 0 ? code : "en"; }
  function t(base, key, vars) {
    var s = (D[base] && D[base][key]) || (D.en && D.en[key]) || (D.fr && D.fr[key]) || key;
    if (vars) s = s.replace(/\{(\w+)\}/g, function (m, k) { return vars[k] != null ? vars[k] : m; });
    return s;
  }
  var loading = {};
  // Base languages that ship a full interface dictionary (/course/i18n/<code>.js).
  // Other base languages keep their word translations but the interface falls back to English.
  var DICTS = ["es", "it", "pt", "de", "nl", "ru", "ar", "he", "zh", "ja", "ko", "tr", "pl"];
  function load(code) {
    code = resolve(code);
    if (D[code]) return Promise.resolve(code);
    if (DICTS.indexOf(code) < 0) return Promise.resolve("en");
    if (!loading[code]) {
      loading[code] = new Promise(function (res) {
        var s = document.createElement("script");
        s.src = "/course/i18n/" + code + ".js";
        s.onload = function () { res(code); }; s.onerror = function () { res("en"); };
        document.head.appendChild(s);
      });
    }
    return loading[code];
  }
  window.I18N = {
    t: t, resolve: resolve, load: load, rtl: function (c) { return !!RTL[c]; },
    add: function (code, dict) { D[code] = dict; },
    available: AVAILABLE,
    dicts: DICTS,
    // [data-i18n="key"] -> textContent, [data-i18n-ph="key"] -> placeholder
    apply: function (base, root) {
      (root || document).querySelectorAll("[data-i18n]").forEach(function (el) { el.textContent = t(base, el.getAttribute("data-i18n")); });
      (root || document).querySelectorAll("[data-i18n-ph]").forEach(function (el) { el.setAttribute("placeholder", t(base, el.getAttribute("data-i18n-ph"))); });
    },
  };
})();
